### ISSUE TITLE
Utenti della stessa organizzazione non vedono i documenti esistenti

### ISSUE THREAD

**Issue by alterat** [italia/docs.italia.it#131]
## Details

Problema con la gestione dei documenti già presenti su Docs Italia per gli utenti con privilegi normali.

## Expected Result

Un membro di un'organizzazione dovrebbe vedere come già presenti su Docs Italia i documenti già compilati della stessa organizzazione. 

## Actual Result

Attualmente, l'utente vede il pulsante "Importa" invece che il collegamento al documento già presente. 
Cliccando sul pulsante, si ottiene il seguente messaggio di errore:

<img width="400" alt="screen shot 2018-08-08 at 17 44 06" src="https://user-images.githubusercontent.com/19559470/43849269-5758997e-9b35-11e8-9678-f93546f56dac.png">

**Comment by xrmx** [comment]
La cosa strana è che i superuser non vedono la possibilità di importare il documento ma un link alla pagina del documento già caricato da altri utenti.

**Comment by xrmx** [comment]
Qui la questione è che i progetti che abbiamo su staging sono ancora privati (Project.privacy_level) quindi li vedono gli admin e i proprietari. Se il progetto fosse pubblico l'utente vedrebbe il link alla pagina del progetto come lo vedono gli admin oggi. Per migliorare l'esperienza possiamo mostrare oltre all'errore del form anche un modo per richiedere un invito a partecipare al progetto. @francescozaia che dici?

**Comment by xrmx** [comment]
Uhm questo dovrebbe essere stato risolto cambiando la visità del documento a pubblico per default e mettendo quella delle versioni a privata.

Reference https://github.com/italia/docs-italia-deploy-scripts/pull/67
