### ISSUE TITLE
Fare un 404 statico per nginx

### ISSUE THREAD

**Issue by xrmx** [italia/docs.italia.it#141]
Da usare al posto di quello di default

**Comment by SimoneNephila** [comment]
@francescozaia Buongiorno, per questa pagina statica includiamo anche il dropdown per la selezione multilingua, ed annessa fascia grigia ( prendendo come riferimento il design al seguente link: https://italia.github.io/design-web-toolkit/components/detail/page--error_404.html ) oppure possiamo omettere entrambe?

**Comment by francescozaia** [comment]
Ciao Simone, il link che hai allegato fa riferimento ad un kit di sviluppo non più utilizzato. L'attuale kit è Bootstrap Italia, con cui è costruito anche il sito di Docs Italia, c'è già una PR che aggiorna l'intero sito all'ultima versione: https://github.com/italia/docs.italia.it/pull/286

Per rispondere alle tue domande, mi sa che va già bene ciò che ha fatto Paolo nella sua PR, intanto mergiamo quella e poi vediamo se rimane altro da sistemare; se c'è da sacrificare qualche funzionalità nelle pagine di errore, non è un problema per adesso.
