### ISSUE TITLE
Stemma amministrazioni

### ISSUE THREAD

**Issue by pablopers** [italia/docs.italia.it#146]
## Stemma Amministrazioni

* è possibile visualizzare lo stemma della propria amministrazione? 
*  è corretto inserire lo stemma all'inizio di ogni documento? 
* è ancora utile avere per ogni repo una cartella /assets/images contenente il file dello stemma richiamato nel file conf.py (dato che il conf.py dovrebbe sparire)?

* Github project URL: https://github.com/cittametropolitananapoli/statuto-cmna-docs*
* Docs Italia project URL (staging): https://docs-italia-staging.teamdigitale.it/cittametropolitananapoli/statuto-cmna/statuto-cmna-docs/it/master/*

## Expected Result

*1)Stemma accanto al nome dell'amministrazione nella sezione "Amministrazioni"*
*2)Stemma all'inizio di ogni documento*

## Actual Result

* lo stemma è visibile all'inizio del documento solo se inserito come immagine nel contenuto del documento*

**Comment by francescozaia** [comment]
1) Riguardo lo stemma accanto al nome dell'amministrazione nella sezione "Amministrazioni": si tratta di una issue che avevamo già discusso su https://github.com/italia/docs.italia.it/pull/96 ma che in effetti era rimasta in sospeso. Grazie per la segnalazione!
2) Riguardo lo stemma nei singoli documenti e tematiche di `conf.py`, informo @pdavide e @xrmx in quanto da discutere a livello di tema, va decisa la soluzione da adottare.

**Comment by xrmx** [comment]
Una cosa facile da implementare è quella di far inserire path assoluti rispetto alla root del repository e costruire noi la url per far prendere al client il file direttamente da github (che dovrebbe servire le immagini con gli header corretti).

**Comment by francescozaia** [comment]
I file publisher_settings.yml contengono già il path relativo alla root del repository (ad esempio `assets/images/cmna_logo.jpg`, `assets/images/logo-italia-512x512.png`, ecc.).

**Comment by xrmx** [comment]
@pablopers in https://github.com/cittametropolitananapoli/italia-conf/blob/master/publisher_settings.yml il logo deve stare fuori da assets come in https://github.com/italia/docs-italia-starter-kit/blob/master/repo-configurazione/publisher_settings.yml

**Comment by pablopers** [comment]
sistemato, grazie Riccardo @xrmx della segnalazione!!

**Comment by xrmx** [comment]
Per 1) c'è la PR qua sopra, per 2) si arriva all'url del logo da publisher.metadata.logo_url

Ma non so se vogliamo considerare il formato dei metadati che ci salviamo una interfaccia pubblica o se piuttosto conviene passare una nuova variabile ai documenti
