### ISSUE TITLE
Homepage: immagini non trovate

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#147]
## Details
Nella [homepage di Staging](https://docs-italia-staging.teamdigitale.it/), ci sono un paio di immagini che tornano un 404 (Not Found):

```
https://docs-italia-staging.teamdigitale.it/media/static/projects/images/book-bg.png
https://docs-italia-staging.teamdigitale.it/media/static/projects/images/documents-bg.png
```
Quei file in effetti non sono presenti tra i sorgenti della cartella [media](https://github.com/italia/docs.italia.it/tree/italia-2.3.13/media/images), ma in teoria ad un certo punto un `collectstatic` dovrebbe copiarcele da `https://github.com/italia/docs.italia.it/tree/italia-2.3.13/readthedocs/projects/static/projects/images`, dove sono presenti.
In locale perlomeno funziona così.

**Comment by xrmx** [comment]
Fatto girare collecstatic, ora ci dovrebbero essere.
