### ISSUE TITLE
Il testo introduttivo all'import della documentazione è in inglese

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#150]
## Details

Appena registrati, la pagina _dashboard_ è titolata "Ready to share your documentation?", ma dovrebbe essere in italiano.

<img width="739" alt="screen shot 2018-08-28 at 16 28 21" src="https://user-images.githubusercontent.com/481084/44729565-67c20e80-aadf-11e8-9ad2-a37aa66dde97.png">

Nel codice [sembra essere ok](https://github.com/italia/docs.italia.it/blob/italia-2.3.13/readthedocs/templates/projects/onboard_import.html#L5), e su [Transifex](https://www.transifex.com/italia/docsitaliait/translate/#it/djangopo/144557686?q=text%3A'Ready+to+share+your+documentation') la traduzione sembra essere corretta ("Pronti per condividere la tua documentazione").

## Expected Result

Il testo dovrebbe essere in italiano

## Actual Result

Il testo è in inglese

**Comment by xrmx** [comment]
Sul branch italia-2.3.13 è buona
![schermata da 2018-08-29 10-06-23](https://user-images.githubusercontent.com/12932/44774360-3bf06880-ab73-11e8-996b-a3c43300c260.png)
