### ISSUE TITLE
Problema con progetti in uno stato inconsistente quando lo YAML di configurazione non è corretto.

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#152]
## Details

Ho provato ad importare un paio di documenti nell'ambiente di pre-produzione:

- https://github.com/italia/anpr
- https://github.com/italia/daf-piano-di-sviluppo

Per entrambi ho avuto lo stesso errore riguardo `invalid document_settings.yml`, molto probabilmente a ragione. Nel primo caso il file non c'è, nel secondo c'è ma forse non era formattato correttamente (ho creato una PR https://github.com/italia/daf-piano-di-sviluppo/pull/10 per sistemarlo).

Detto questo, ora vedo i due progetti in uno stato "inconsistente":
<img width="764" alt="screen shot 2018-08-28 at 17 16 36" src="https://user-images.githubusercontent.com/481084/44732682-27b25a00-aae6-11e8-8099-0277ac5cc49d.png">

Che si traduce in questa schermata se provo a cliccare su uno dei due:
<img width="938" alt="screen shot 2018-08-28 at 17 17 04" src="https://user-images.githubusercontent.com/481084/44732717-38fb6680-aae6-11e8-8fef-035b02d5e9e1.png">

In attesa dell'approvazione della PR (e quindi ad avere un file `document_settings.yml` corretto), mi domandavo se poi riuscirò a compilare quei documenti.

**Comment by xrmx** [comment]
I progetti dovrebbero venir cancellati se all'importazione i metadata sono invalidi, che versione di italia-2.3.13 c'è in produzione?

**Comment by alterat** [comment]
Strano perché invece su Staging la compilazione di quei documenti fallisce con lo stesso messaggio ma poi "rimbalza" mostrando i repo come non ancora importati.

**Comment by francescozaia** [comment]
Infatti ne parlavamo con @xrmx, si tratta solo di un fix da portare in produzione. Meglio così!

**Comment by francescozaia** [comment]
Tutto ok ora! 🥇
