### ISSUE TITLE
Filter not working in Docs Italia API

### ISSUE THREAD

**Issue by pdavide** [italia/docs.italia.it#156]
## Details

Filtering by project slug returns an empty set in https://docs-italia-staging.teamdigitale.it/docsitalia/api/document/?project={project slug}

## Expected Result

The project identified by the given slug.

## Actual Result

An empty set is returned.

**Comment by pdavide** [comment]
Side question: is the project slug unique in the general scope? Or is it unique in the publisher/publisher_project scope?

**Comment by francescozaia** [comment]
Theoretically, we can have two projects with the same name/slug for two different publishers, but we haven't done much yet to investigate on that.

**Comment by xrmx** [comment]
As the project slug is not globally unique you have to filter by both project and publisher and the same time to have the results you want.

**Comment by xrmx** [comment]
Works for me, looks more like a confusion between the document slug and project slug.

**Comment by pdavide** [comment]
Working as intended. Closing.
