### ISSUE TITLE
Documenti con lo stesso titolo

### ISSUE THREAD

**Issue by alterat** [italia/docs.italia.it#161]
## Details

Se provo a importare un documento con lo stesso titolo (per la precisione, lo stesso `name` nel document_settings.yml) di uno esistente, ottengo il seguente errore:

<img width="547" alt="screen shot 2018-08-29 at 17 59 00" src="https://user-images.githubusercontent.com/19559470/44801824-644f8580-abba-11e8-95a7-c4d57046209a.png">

Questo significa che due comuni diversi, per esempio, non possono avere entrambi un documento chiamato "Circolare FOIA". È il comportamento che vogliamo ottenere?

**Comment by xrmx** [comment]
Se Project.name ha un attributo unique diventa un problema, ma potrebbe essere una PR fattibile upstream. Per lo slug possiamo farci furbi e aggiungerci qualcosa per renderlo unico.
