### ISSUE TITLE
Documenti privati tornano 404

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#164]
## Dettagli

Lo scrivo giusto come reminder, anche se credo sia già stato risolto e debba solo essere deployato in produzione: ogni nuovo documento importato (che è in stato _private_ by default), non permette al publisher stesso di essere visionato. È necessario agire sulla tendina dedicata e renderlo _public_ per poterlo vedere; questo ovviamente ha il side-effect di rendere il documento disponibile a tutti.

<img width="962" alt="screen shot 2018-08-30 at 12 43 22" src="https://user-images.githubusercontent.com/481084/44847205-fb681c00-ac52-11e8-81aa-72a59951a4b0.png">

## Risultato che ci si aspettava

Anche i documenti in stato _private_ devono essere visibili ai gestori del documento stesso.

## Risultato effettivo

I documenti in stato _private_ vanno in 404.

**Comment by xrmx** [comment]
quella è la privacy delle *build* non del *documento*

**Comment by francescozaia** [comment]
Verificherò meglio il comportamento e, in caso sia tutto ok, chiudo.

**Comment by xrmx** [comment]
Voglio dire che i progetti devono essere in stato pubblico mentre le build in stato privato. Se l'utente non vede le build quando sono in stato privato è un bug. Se non vede le build perchè il documento è in stato privato è da sistemare dall'admin. Lo screenshot che hai mandato tu mostra il privacy level perciò il titolo e la descrizione sono fuorvianti perchè ci sono due privacy level :)

**Comment by francescozaia** [comment]
Devo ammettere che il comportamento non è chiaro, provo a spiegarmi meglio:
Ogni volta che importo un nuovo documento, cliccando sul "+" nella schermata apposita, viene lanciata una compilazione che anche se va a buon fine non mi permette di vedere il mio documento.
Questa è la situazione in cui mi ritrovo con:
https://w1.docs.iast.it/italia/data-analytics-framework/pianotri-elencobasidatichiave/it/bozza/
(404 Not Found - nginx)

Se poi cambio la tendina mostrata nella issue da _"privato"_ a _"pubblico"_, allora riesco a vedere la documentazione. Questo è il caso di:
https://w1.docs.iast.it/italia/data-analytics-framework/pianotri-schede-bdin/it/bozza/
(e di tutte le altre documentazioni)

Questa situazione non è corretta poiché impone di rendere pubbliche le documentazioni prima di poterle vedere, anche essendone il publisher.

**Comment by xrmx** [comment]
Qui la questione credo sia che nel caso di build private non possiamo andare dritti su quel tipo di url ma dobbiamo passare per serve_docs (o qualcosa del genere) dell'applicazione django. A quanto ricordo quell'url è gestita da nginx che punta a public_root (o simile) mentre le build private vanno in private_root. Quindi credo sia da cambiare il nostro resolver per tornare l'url di serve_docs piuttosto che andare dritti su quella di nginx (almeno se la versione della build non è pubblica).

**Comment by paoloromolini** [comment]
@francescozaia questa è ancora valida?

**Comment by francescozaia** [comment]
Eh mi sa di sì @paoloromolini , vedi lo stato in cui è `italia/pianotri-elencobasidatichiave`: se vuoi ti elimino il progetto così puoi provare a ri-importarlo, fammi sapere.

**Comment by francescozaia** [comment]
Confermo, ho provato a cancellare e ricreare il documento `italia/daf-dataportal-it-docs` e finché non ho cambiato il menu nella tendina da _"privato"_ a _"pubblico"_ il documento tornava 404.

**Comment by paoloromolini** [comment]
PR: https://github.com/italia/docs.italia.it/pull/197

**Comment by francescozaia** [comment]
Succedono cose strane, non so se sto sbagliando qualcosa io ma secondo me ci sono problemi con gli URL. Gli URL con `/publisher/project/` non sono accessibili nemmeno da utente loggato, lo sono invece correttamente quelli con `/docs/` (che però non sono quelli "canonici").
![ezgif com-resize](https://user-images.githubusercontent.com/481084/46420624-c0b14200-c730-11e8-9e6f-44145ac9fd57.gif)

**Comment by paoloromolini** [comment]
Il serving dei doc privati e il serving dei doc pubblici devono per forza passare da due url diverse.
Questo perchè vengono servite la prima da django e la seconda de nginx.
Quindi ogni volta che cambi la privacy level di un documento devi cliccare su view docs.
E' normale che ti ritorni un 404 quattro sulla url servita da ngnix quando è in stato privato e da loggato perchè deve passare da django che sa effettivamente se un utente è loggato o meno.

**Comment by francescozaia** [comment]
Ok, si può mergiare #197.
Il comportamento non è ancora perfetto dal punto di vista del publisher (mi ci vedo a spiegare al povero dipendente PA che una è servita da django e l'altra da nginx... 😄), ma per ora la consideriamo accettabile.
