### ISSUE TITLE
URL del documento

### ISSUE THREAD

**Issue by alterat** [italia/docs.italia.it#165]
## Dettagli

Al momento, la struttura dell'URL è del tipo: `org/proj/nome-repository`. 
Secondo me avere `nome-repository` lì non è ideale, visto che molti repo nell'organizzazione Italia hanno nomi in inglese.  

## Proposta

Si potrebbe usare il parametro `short_name`, già previsto nel document_settings.yml, per costruire l'URL del documento. A quel punto, `short_name` diventerebbe obbligatorio e non più opzionale. 

Si potrebbe poi pensare di estendere lo stesso meccanismo a organizzazione e progetti, in modo da uniformare la creazione degli URL.

**Comment by xrmx** [comment]
Se disposnibile short_name viene già usato per i progetti per creare lo slug

**Comment by alterat** [comment]
@xrmx solo per i progetti, o anche per publisher e documenti?

**Comment by xrmx** [comment]
A memoria solo per i progetti

**Comment by francescozaia** [comment]
Sarebbe bene poter personalizzare l'URL anche per i documenti
