### ISSUE TITLE
Homepage e pagine Amministrazione: link ad amministrazioni inconsistenti

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#166]
## Dettagli
Da https://w1.docs.iast.it/, cliccando sul _progetto_ "Data & Analytics Framework", a volte porta correttamente su https://w1.docs.iast.it/italia/daf/, altre porta su https://w1.docs.iast.it/italia/data-analytics-framework/ che non è corretto. Avviene anche per la documentazione "Regole tecniche" di SPID, il cui progetto linka a https://w1.docs.iast.it/italia/sistema-pubblico-di-identita-digitale/ anziché https://w1.docs.iast.it/italia/spid/.

A naso, sembra sia stato introdotto un errore di recente perché le documentazioni importate la scorsa settimana sono ok, mentre le nuove no.

Questo disallineamento avviene anche nelle pagine delle singole amministrazioni (es: https://w1.docs.iast.it/italia/daf/).

## Risultato che ci si aspettava

Tutti i link ai progetti devono portare alla pagina corretta.

## Risultato effettivo

Alcuni link ai progetti non portano alla pagina corretta; non mi è chiaro da dove arrivino quegli slug errati, come ad esempio:
`data-analytics-framework` anziché `daf`
`sistema-pubblico-di-identita-digitale` anziché `spid`

**Comment by paoloromolini** [comment]
@francescozaia questo avviene ancora dopo l'ultimo deploy? Non riesco a riprodurre il bug.

**Comment by francescozaia** [comment]
Sì, ho provato a cancellare e ri-importare questo documento:
https://w1.docs.iast.it/italia/data-analytics-framework/daf-dataportal-it-docs/it/bozza/
(che sarebbe `italia/daf-dataportal-it-docs`) ed ora nella homepage il link all'amministrazione "Data & Analytics Framework" punta a https://w1.docs.iast.it/italia/data-analytics-framework/ anziché a https://w1.docs.iast.it/italia/daf/.

**Comment by paoloromolini** [comment]
Ci sono doppi publisher projects , quelli nuovi hanno uno slug diverso.  Credo sia legata a questa : https://github.com/italia/docs.italia.it/issues/143

**Comment by paoloromolini** [comment]
Questa è sistemata, le vecchie documentazioni buildate (sotto al vecchio publisher) vanno cancellate a mano sul server. Questo naturalmente non sarà più necessario dopo aver mergiato questa : https://github.com/italia/docs.italia.it/pull/177
