### ISSUE TITLE
Nelle pagine di Amministrazione e nella ricerca sono visibili documenti privati

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#167]
## Dettagli

Da https://w1.docs.iast.it/ non è visibile la documentazione https://w1.docs.iast.it/italia/data-analytics-framework/pianotri-elencobasidatichiave/it/bozza/ (che va in 404 come descritto in https://github.com/italia/docs.italia.it/issues/164), ma entrando nella pagina del singolo progetto https://w1.docs.iast.it/italia/daf/ la documentazione compare (Elenco basi di dati chiave).

## Risultato che ci si aspettava

La documentazione _"Elenco basi di dati chiave"_ non dovrebbe mai comparire.

## Risultato effettivo

La documentazione _"Elenco basi di dati chiave"_ è raggiungibile dalla pagina https://w1.docs.iast.it/italia/daf/ o cercando "Elenco basi di dati chiave", e possibilmente in altri modi.

**Comment by paoloromolini** [comment]
Pr: https://github.com/italia/docs.italia.it/pull/169

**Comment by paoloromolini** [comment]
Questa dovrebbe essere ok

**Comment by paoloromolini** [comment]
@francescozaia posso chiudere questa?

**Comment by paoloromolini** [comment]
https://w1.docs.iast.it/projects/pianotri-elencobasidatichiave/ questa risulta public ora come Project Privacy Level

**Comment by francescozaia** [comment]
Fixed
