### ISSUE TITLE
I titoli della card troppo lunghi vanno in overflow

### ISSUE THREAD

**Issue by paoloromolini** [italia/docs.italia.it#173]
## Dettagli
La card del progetto con titoli troppo lunghi va in overflow.
Succede nella home page e nelle pagine di dettaglio di publisher projects
![2018-09-05-170710_792x735_scrot](https://user-images.githubusercontent.com/12033921/45102709-974fc700-b12e-11e8-90f3-b29c157c6ae0.png)

## Risultato che ci si aspettava
Un truncatewords sui titoli troppo lunghi.

## Risultato effettivo

I titoli troppo lunghi vanno in overflow

**Comment by pdavide** [comment]
Nella vecchia [homepage di Docs Italia](https://docs.developers.italia.it/) il codice che fixava questa issue si trova [qui](https://github.com/italia/docs.developers.italia.it/blob/master/_includes/scripts.html#L32-L49).
Necessita di [due piccole librerie js](https://github.com/italia/docs.developers.italia.it/blob/master/_includes/scripts.html#L14-L15): [clamp.js](https://github.com/josephschmitt/Clamp.js) e [jQuery TextFill](https://github.com/jquery-textfill/jquery-textfill). Purtroppo nessuna delle due mi sembra sia disponibile via npm.
Include anche una soluzione cross-browser per troncare la descrizione del documento a 3 righe. Attualmente il CSS usa la regola `-webkit-line-clamp: 3` che però [non mi sembra molto ben supportata dai diversi browser](https://caniuse.com/#search=clamp).
