### ISSUE TITLE
L'eliminazione di un publisher non innesca la cancellazione dei file statici dei documenti

### ISSUE THREAD

**Issue by pdavide** [italia/docs.italia.it#174]
## Dettagli

L'eliminazione del publisher elimina a cascata anche il publisher_project e tutti i documenti [funzionalità aggiunta con questa PR](https://github.com/italia/docs.italia.it/pull/113).
Al vecchio URL le documentazioni risultano ancora disponibili.
Inoltre all'eliminazione del publisher non consegue anche l'eliminazione della corrispettiva "Remote organization" che quindi continua ad apparire nel frontend tra quelle abilitate all'importazione di documenti.

## Risultato che ci si aspettava

Ai vecchi URL dovrebbe essere restituito un 404.
L'organizzazione GitHub non dovrebbe apparire tra quelle abilitate all'importazione.

## Risultato effettivo

Le documentazioni risultano ancora disponibili e l'organizzazione è elencata nella pagina di importazione dei nuovi documenti.

**Comment by paoloromolini** [comment]
pr: https://github.com/italia/docs.italia.it/pull/177

**Comment by paoloromolini** [comment]
@pdavide Questa è deployata sia su stage che su produzione. Non so se hai modo di provarla con qualche progetto

**Comment by pdavide** [comment]
@paoloromolini provato su staging.
Purtroppo non funziona. Ho eliminato il mio publisher `docs-theme-org` dal backoffice di Django, ma la documentazione all'URL https://docs-italia-staging.teamdigitale.it/docs-theme-org/progetto-tema/design-docs-test/it/bozza/ risulta ancora raggiungibile.
