### ISSUE TITLE
L'email di reset password non ha un'immagine di testata

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#175]
## Dettagli
Come da schermata allegata:
<img width="1233" alt="screen shot 2018-09-06 at 14 00 17" src="https://user-images.githubusercontent.com/481084/45156054-4945cc80-b1dd-11e8-90a3-38efd5b0f187.png">
Verificato sia su staging che su produzione.

## Risultato che ci si aspettava

Un'immagine che identifichi il sito da cui arriva l'email.

## Risultato effettivo

Manca l'immagine.

**Comment by paoloromolini** [comment]
Io riesco a vedere l'immagine sia su staging  che su produzione con thunderbird mentre non la vedo su gmail.

![2018-09-06-144302_958x593_scrot](https://user-images.githubusercontent.com/12033921/45158080-39c98200-b1e3-11e8-8338-848f87924391.png)

Probabilmente è il base64 che non gli piace

**Comment by francescozaia** [comment]
Curioso, ci sono pareri contrastanti ([1](https://stackoverflow.com/questions/3279523/base64-images-to-gmail/12786336#12786336)) ([2](https://stackoverflow.com/questions/46783599/base64-encoded-image-is-not-showing-in-gmail/46789485)) sul supporto a base64 su Gmail.

Se non se ne vien fuori in altro modo con path relativi, una volta online potremo mettere anche un path assoluto (attualmente https://w1.docs.iast.it/media/docsitalia/images/docs-italia-email.png).

**Comment by paoloromolini** [comment]
RTD fa così: https://github.com/rtfd/readthedocs.org/blob/master/readthedocs/templates/core/email/base.html#L66

**Comment by francescozaia** [comment]
Eh appunto, facciamo anche noi uguale. Mettiamo un link a  https://docs.italia.it/media/docsitalia/images/docs-italia-email.png, che in teoria quando andiamo online funzionerà. #backtothefuture

**Comment by paoloromolini** [comment]
La pr è qui, dobbiamo solo decidere quando mergiarla: 
https://github.com/italia/docs.italia.it/pull/181
