### ISSUE TITLE
Review documentazione deployment scripts

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#176]
## Dettagli

Verificare il readme dei role ansible per documentare alcuni comandi operativi per:

* Fare il deployment degli aggiornamenti "standard" di RTD su staging e produzione
* Fare il deployment degli aggiornamenti del convertitore su staging e produzione
* Fare il deployment di branch specifici di RTD su staging e produzione

**Comment by pdavide** [comment]
Ottimo così!
Non ricordo se è già documentato, ma c'era un comando per innescare la rebuild di tutti i documenti. Ci sono anche altri comandi custom che abbiamo creato?
cc @yakky @francescozaia

**Comment by paoloromolini** [comment]
@pdavide  Eccoli https://github.com/italia/docs.italia.it/wiki/Comandi-utili

**Comment by francescozaia** [comment]
Il processo è stato documentato su un [documento privato](https://docs.google.com/document/d/1awcvct9feoWfgnn98lgM_rZAbk2FdGljEGSlWYdI-3Q).
