### ISSUE TITLE
La pagina di ricerca dei tag mostra i nomi (e link) degli account

### ISSUE THREAD

**Issue by pdavide** [italia/docs.italia.it#178]
## Dettagli

* Pagina web del progetto su Docs Italia: https://docs-italia-staging.teamdigitale.it/projects/tags/linee-guida/

## Risultato che ci si aspettava

Visualizzare tutti i documenti con uno specifico tag.

## Risultato effettivo

Accanto ad ogni documento è mostrato il nome dell'utente proprietario linkato alla pagina del profilo corrispondente. Penso che i nomi dei proprietari dei documenti non debbano essere mostrati né linkati.
Nice to have: si potrebbero linkare il progetto e il publisher di appartenenza di ciascun documento.

**Comment by francescozaia** [comment]
La PR associata a questa issue è mergiata, probabilmente si può chiudere. Chiederei una verifica da parte di @pdavide una volta deployata.

**Comment by pdavide** [comment]
Da una verifica, la PR non ha risolto il problema.
Verifico un nuovo branch su staging e procedo con una nuova PR.

**Comment by francescozaia** [comment]
Sistemo io un po' la UI

**Comment by francescozaia** [comment]
Ho fatto in modo di avere una pagina sensata (come sempre alla cieca); ovviamente andrebbe migliorata mostrando i documenti come "card", ma lo affronteremo in un prossimo task.
