### ISSUE TITLE
Metadati non presenti nel context della build

### ISSUE THREAD

**Issue by pdavide** [italia/docs.italia.it#183]
Nel caso di un documento in cui il file `conf.py` non si trova nella root del repo (ad esempio [18app-esercenti-docs](https://github.com/italia/18app-esercenti-docs)), i dati del file `document_settings.yml` non arrivano al build context.
Questo accade perché il [codice che aggiungiamo](https://github.com/italia/docs.italia.it/blob/6639619848f1a7af67f9eefd355735511fc85d64/readthedocs/templates/doc_builder/conf.py.tmpl#L149) al `conf.py` assume che il file `document_settings.yml` si trovi nella stessa directory.

Questo causa il fallimento della compilazione perché il tema assume che i metadati del documento siano sempre presenti nel context della build.

A valle del fix di questo bug, penso sia utile uniformare la struttura di tutti i repo dei documenti seguendo lo schema che suggerivo [qui](https://docs.google.com/document/d/1KxqDqT-ydveMc2_eQbDVSt-73Toc-auUPvOcNbUDLwg/edit#heading=h.ipae3kuulo2e).
Questa considerazione vale solo per i nuovi documenti perché la struttura del repo impatta sullo schema degli URL generati, quindi eventuali modifiche a documenti esistenti implicherebbero la creazione di un sistema di redirect interno che al momento aggiungerebbe solo entropia e mal di testa.

cc @francescozaia

**Comment by francescozaia** [comment]
Mi trovi d'accordo riguardo la struttura dei nuovi documenti, il documento che hai linkato potrebbe divenire parte della guida alla pubblicazione (cc @atorin).

Se ho ben capito, la modifica in questione dovrebbe invece cercare sempre nella root del repository a prescindere da dove si trovi il `conf.py`

**Comment by paoloromolini** [comment]
PR: https://github.com/italia/docs.italia.it/pull/186

Ho impostato la lettura del document settings sempre alla root del progetto e tolto il try except. Così il log è un po' più chiaro

**Comment by pdavide** [comment]
Fixed in #186.
