### ISSUE TITLE
Senza `conf.py` il file index.rst rischia di essere scartato

### ISSUE THREAD

**Issue by pdavide** [italia/docs.italia.it#193]
## Dettagli

Quando si creano documenti da repo che non hanno il `conf.py` (che in futuro sarà la regola), il codice di docs italia [cerca il master_doc](https://github.com/italia/docs.italia.it/blob/1d252888030a01f81689747fb85e4431ac9e23ee/readthedocs/doc_builder/backends/sphinx.py#L150) (che normalmente è il file `index.rst`) usando [una funzione](https://github.com/italia/docs.italia.it/blob/1d252888030a01f81689747fb85e4431ac9e23ee/readthedocs/doc_builder/base.py#L96) che a sua volta fa [un'altra chiamata](https://github.com/italia/docs.italia.it/blob/1d252888030a01f81689747fb85e4431ac9e23ee/readthedocs/doc_builder/base.py#L98) per sapere in quale directory cercare il `master_doc`.
La funzione [`docs_dir`](https://github.com/italia/docs.italia.it/blob/1d252888030a01f81689747fb85e4431ac9e23ee/readthedocs/doc_builder/base.py#L83) effettua una ricerca, a partire dalla root del repo del documento, di nomi di subdirectory contenuti in una lista predefinita (`['docs', 'doc', 'Doc', 'book']`). Succede quindi che, se una di queste subdirectory esiste, diventa il valore della variabile `docs_dir`.
La funzione chiamante `create_index ` cerca quindi il `master_doc` nella directory `docs_dir` e, se non lo trova, ne genera uno (che è semplicemente un placeholder definito staticamente nel codice).
Il bug sta nel fatto che, se non esiste il `conf.py` ed esiste un directory tra quelle definite nella lista, allora il file `index.rst` che dovesse trovarsi nella root del repo viene ignorato.

Questo è il caso del repo https://github.com/docs-theme-org/design-docs-test che è un fork del repo https://github.com/italia/design-docs privato del suo `conf.py`.

Il risultato della build è: https://docs-italia-staging.teamdigitale.it/docs-theme-org/progetto-tema/design-docs-test/it/bozza/.

Propongo una PR che vincoli la variabile `docs_dir` alla sola root del repo del documento. Questo è anche coerente con la strutturazione dei repo per i documenti di Docs Italia che abbiamo indicato nella guida.

**Comment by pdavide** [comment]
cc @francescozaia @atorin

**Comment by francescozaia** [comment]
Sulla carta sono assolutamente d'accordo.
Temo che questa impostazione però, allo stato attuale, si scontri con alcuni documenti già pubblicati che si trovano dentro cartelle dedicate (vedi  commenti nel file https://github.com/italia/italia-conf/blob/master/projects_settings.yml). In tal caso, questi documenti andrebbero rivisti/estratti dai repository di appartenenza (penso ad un `anpr-docs` ad esempio).

**Comment by alterat** [comment]
Però i documenti a cui fai riferimento stanno tutti in cartelle tipo `rst` o `src`. Se capisco correttamente, il problema che indica @pdavide si verifica solo quando il nome della cartella fa parte di quella lista. Quindi non dovrebbe verificarsi per i nostri documenti, giusto?

**Comment by pdavide** [comment]
@francescozaia per quei documenti che hanno index.rst dentro una subdirectory si può sempre specificare il path manualmente. Su RTD si può fare da "impostazioni avanzate" nel campo "File di configurazione Python" che però non abbiamo su Docs Italia.
Abbiamo già importato il [repo anpr](https://github.com/italia/anpr) su Docs Italia?
Funziona anche senza impostare il campo "File di configurazione Python"?

**Comment by francescozaia** [comment]
@pdavide pare di sì, non so come a questo punto!
In caso di necessità possiamo sicuramente ripristinare l'opzione presente su RTD.

**Comment by pdavide** [comment]
La build di anpr va a buon fine perché il `conf.py` viene cercato in tutto il repo. Poi la directory che lo contiene diventa quella nella quale RTD cerca il file `index.rst`.
La issue che segnalo si manifesta invece quando non è presente il `conf.py`.
Per casi (immagino sporadici) come quello di anpr basta mettere un conf.py minimale nella directory che contiene `index.rst` oppure specificare il path manualmente nell'opzione apposita.
In generale ritengo che la soluzione che propongo per la issue sia nella direzione giusta visto che andremo, a tendere, ad eliminare il `conf.py`. I pochi casi _legacy_ che si presenteranno li possiamo gestire ad hoc.

Ovviamente tutto questo andrebbe documentato nella guida.

**Comment by francescozaia** [comment]
PR #194 mergiata, lascio aperta per test.
