### ISSUE TITLE
Escludere dall'endpoint delle API le versioni private

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#198]
## Dettagli
Escludere dall'endpoint `docsitalia/api/document/[project-slug]/active_versions/` le versioni private. I motivi sono due:
- la versione non è più così "privata"
- la versione appare nel menu a tendina di tutte le versioni del documento

**Comment by paoloromolini** [comment]
PR: https://github.com/italia/docs.italia.it/pull/196
