### ISSUE TITLE
Guida tecnica all’uso di metriche per il software applicativo sviluppato per conto delle pubbliche amministrazioni

### ISSUE THREAD

**Issue by alterat** [italia/docs.italia.it#2]
Questo è il risultato della prima conversione del documento "Guida tecnica all’uso di metriche per il software applicativo sviluppato per conto delle pubbliche amministrazioni".

[Guida-tecnica.zip](https://github.com/italia/docs.italia.it/files/1833901/Guida-tecnica.zip)

**Comment by alterat** [comment]
Visto che il documento nel frattempo è stato pubblicato, credo che questa issue si possa tranquillamente chiudere.

**Comment by yakky** [comment]
Grazie per l'update

**Comment by danse** [comment]
Si, abbiamo gestito questa conversione aggiungendo il file qui https://github.com/italia/pandoc-docs2rst/commit/30c4d4bbf68dcf35dedde4adf3b8b82b67b377f2, non mi ero reso conto che questa issue fosse rimasta aperta
