### ISSUE TITLE
Repo cancellati ancora visibili fra quelli importabili

### ISSUE THREAD

**Issue by alterat** [italia/docs.italia.it#203]
## Dettagli

Un repo cancellato dall'organizzazione GitHub appare ancora fra i documenti importabili su Docs Italia. 
In particolare, il repo `siti-web-scuole-docs` appare ancora fra i repo disponibili per l'importazione, anche se quel repo è stato rimosso. Se si prova a importare il documento, si ottiene l'errore "nessun document_settings disponibile".

## Risultato che ci si aspettava

Rimuovere il repo dall'organizzazione dovrebbe automaticamente cancellare il documento da Docs Italia?

**Comment by francescozaia** [comment]
Sembra accadere lo stesso anche per i repo rimossi dal file `italia-conf`. In particolare, ho [rimosso](https://github.com/italia/italia-conf/commit/1407bb4da14efecc2704ac61173f4f4903207081) `cad-docs` dall'organizzazione _Italia_, ma tale repo risulta ancora importabile dal pannello di amministrazione.

**Comment by paoloromolini** [comment]
PR: https://github.com/italia/docs.italia.it/pull/221

**Comment by paoloromolini** [comment]
Avete modo di fare un prova? (probabilmente dopo il sync dovrete fare un refresh della pagina)

**Comment by Amanit** [comment]
Dopo cancellazione di Repo bisogna modificare anche `project_settings.yml` togliendo il progetto cancellato dal documents list. Dopo questo il progetto non e' piu importabile.

**Comment by yakky** [comment]
@francescozaia come documentiamo il comportamento corretto?
