### ISSUE TITLE
Far sì che i "Documenti in evidenza" siano davvero tali

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#206]
## Dettagli

Al momento i documenti in homepage sono mostrati semplicemente in base alla compilazione più recente. Alcuni documenti di fondamentale importanza, come il CAD, le Linee Guida di Design ed altro sarebbe bene fossero portati sempre in alto.

Per ora, con [ispirazione ai layout](https://projects.invisionapp.com/d/main#/console/11609034/308339651/preview), si potrebbero mostrare 8 documenti curati "a mano", seguiti dai più recenti identificati da opportune titolazioni.

**Comment by yakky** [comment]
Chiudo, rimane attivo nella board di testing

**Comment by francescozaia** [comment]
<img width="1134" alt="Screenshot 2019-12-23 at 10 40 10" src="https://user-images.githubusercontent.com/481084/71350089-c8951600-2570-11ea-8ab0-c223023a727c.png">
Allego solo per poter aggiungere alla wiki ;)

**Comment by francescozaia** [comment]
Aggiornata: https://github.com/italia/docs.italia.it/wiki/Come-classificare-i-%22Documenti-in-evidenza%22
