### ISSUE TITLE
Invalidare la cache di ElasticSearch

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#210]
## Dettagli

Al momento, la ricerca torna tra i risultati anche documenti che sono stati rimossi (`design-docs`), i cui link ovviamente non funzionano. Penso si tratti solo di cache ES, per cui dovremmo assicurarci di ripulire eventuali disallineamenti.

**Comment by yakky** [comment]
@francescozaia questo https://github.com/italia/docs.italia.it/wiki/Indici-ES è sufficiente?

**Comment by francescozaia** [comment]
Yep.
