### ISSUE TITLE
Notifica per nuove build dei documenti

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#212]
## Dettagli

Per mantenere un migliore controllo sulle documentazioni, vorremmo attivare un canale Slack che notifichi ogni build di nuovi documenti.

**Comment by yakky** [comment]
@francescozaia puoi dettagliare un po' di più questa feature?

**Comment by francescozaia** [comment]
Vorremmo avere un'integrazione con Slack per cui ad ogni build in produzione venga invitato un messaggio su un canale dedicato che andremo a creare su Slack, sfruttando gli [hook di Slack](https://api.slack.com/messaging/webhooks).

È una vecchia issue a bassa priorità di cui devo capire la necessità e il costo, aggiorno io nel caso la issue con i dettagli per la configurazione necessaria (nuovo canale ed eventuali keys). Per ora la parcheggio un attimo.

**Comment by yakky** [comment]
Segno qui un pacchetto possibilmente utile allo scopo https://github.com/lamby/django-slack
