### ISSUE TITLE
Gestione documenti in altre lingue

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#214]
## EPIC

Ci siamo scontrati con la difficoltà di avere la versione tradotta di un documento, al momento alcuni documenti tradotti sono completamente scollegati tra loro:

- https://docs.italia.it/italia/developers-italia/lg-acquisizione-e-riuso-software-per-pa-docs/it/stabile/
- https://docs.italia.it/italia/developers-italia/gl-acquisition-and-reuse-software-for-pa-docs/en/stabile/

oppure

- https://docs.italia.it/italia/developers-italia/publiccodeyml/it/master/
- https://docs.italia.it/italia/developers-italia/publiccodeyml-en/en/master/

Per il piano triennale si è riusciti ad avere entrambe allo stesso URL, ma non mi è chiaro perché le versioni non sono allineate.

- https://docs.italia.it/italia/piano-triennale-ict/pianotriennale-ict-doc/it/2019-2021/
- https://docs.italia.it/italia/piano-triennale-ict/pianotriennale-ict-doc/en/stabile/

Sicuramente è necessario il ripristino dell'opzione "Translations" sotto le "Impostazioni Avanzate" per i publisher, che permette di collegare due documenti in lingue diverse.

Sarà inoltre necessario verificare che si riesca a switchare tra una lingua e l'altra semplicemente cambiando il `locale` nell'URL.

**Comment by yakky** [comment]
@francescozaia da tenere presente che sono già gestite da RTD le relazioni di "documento tradotto" https://docs.readthedocs.io/en/stable/localization.html

Il link alla sezione relativa è attualmente commentato (volutamente)

**Comment by francescozaia** [comment]
Sì ricordo il fatto che fosse commentato, e sicuramente quella è una cosa da ripristinare.
Per il resto, avevo creato un epic proprio perché volevo fare un attimo di ricerca e definire le attività prima di lavorarci. Lo farò, forse.

**Comment by yakky** [comment]
si si, era solo un appunto per non perdere traccia di quello che già è disponibile
