### ISSUE TITLE
Per admin è impossibile fare wipe dell'ambiente di build per projects di altri utenti

### ISSUE THREAD

**Issue by pdavide** [italia/docs.italia.it#215]
Da utente admin ricevo un 404 se cerco di fare wipe dell'ambiente di build di un project non di mia proprietà.
Esempio:
- https://docs.italia.it/wipe/[mio-progetto]/bozza/ => ok
- https://docs.italia.it/wipe/[progetto-altrui]/bozza/ => 404

**Comment by paoloromolini** [comment]
Questa modifica al codice di RTD permette ai superuser di fare il wipe di tutti i progetti:
https://github.com/italia/docs.italia.it/pull/227

**Comment by Amanit** [comment]
@pdavide controla un altra volta per favore

**Comment by yakky** [comment]
@francescozaia questo può essere ritestato su staging, dovrebbe essere giầ risolto
L'ho aggiunto anche alla board di test

**Comment by pdavide** [comment]
Confermo risoluzione della issue in staging.

**Comment by yakky** [comment]
Ottimo, grazie. chiudo allora
