### ISSUE TITLE
Miglioramenti risultato ricerca

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#216]
## Dettagli

La SERP al momento è un po' caotica e poco chiara nei contenuti.

Si dovrebbero sistemare intanto le seguenti cose:
- Mostrare un solo esempio (non due) di snippet con il testo ricercato
- Mostrare titoli dei progetti e dei documenti anziché i loro _slug_
- Stilizzare l'evidenziazione del testo trovato in questo modo:
```
.document-card-description em {
    background: #bffffd;
    font-weight: 700;
}
```

Allego screenshot per chiarire i primi due punti:
<img width="1119" alt="screenshot 2018-10-11 at 11 07 29" src="https://user-images.githubusercontent.com/481084/46793640-881ff280-cd46-11e8-946a-f21f2403d921.png">

**Comment by yakky** [comment]
Direi che è chiusa con il merge di #217
