### ISSUE TITLE
Le pagine inesistenti con un path che corrisponde ad un documento non tornano 404

### ISSUE THREAD

**Issue by pdavide** [italia/docs.italia.it#218]
Tutte le pagine inesistenti con path:
`/<publisher>/<progetto>/<documento>/<lingua>/<versione>/<pagina inesistente>` non restituiscono un errore ma la homepage del documento.

**Comment by pdavide** [comment]
Sembra che il bug sia ancora (o di nuovo) presente.

**Comment by Amanit** [comment]
@pdavide non riesco a riprodurre il bug

**Comment by pdavide** [comment]
@Amanit visita https://docs-italia-staging.teamdigitale.it/AgID/documenti-in-consultazione/lg-cert-regionali/it/bozza/nonexistent.html

**Comment by yakky** [comment]
@Amanit 
secondo me è questa riga qua https://github.com/italia/docs.italia.it/blob/italia-dev/docker/nginx/sites-available/readthedocs-main.conf#L99

se vedi usa esplicitamente degli index.html se $path non esiste

puoi verificare se senza togliendo il riferimento a index.html torna correttamente un 404

ed eventualmente possiamo capire se gestire in modo diverso il fallback su `index.html` per la root

**Comment by Amanit** [comment]
@pdavide abbiamo modificato i settings sul server di staging.
Potrebbe testare?

**Comment by yakky** [comment]
@pdavide @francescozaia il fix per questa è deployato su staging
