### ISSUE TITLE
Webhook non attivabili

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#222]
## Dettagli

Per Documenti creati da utenti che non erano i rispettivi owner, ora non sembra possibile aggiungere un webhook. Attualmente, ad esempio il [documento "regole tecniche di SPID"](https://docs.italia.it/dashboard/spid-regole-tecniche/) riporta la dicitura, ereditata da RTD:

> Questo repository non ha impostato un webhook valido, i commit non lanceranno nuove build del documento. 
> Vedi le integrazioni del tuo documento per maggiori informazioni.

Andando nell'area "[integrazioni](https://docs.italia.it/dashboard/spid-regole-tecniche/integrations/)", ho provato a rimuovere/riaggiungere il "webhook per github", ma il messaggio d'errore rimane e, di conseguenza, nuovi commit sul repo non lanciano la build del documento.

**Comment by francescozaia** [comment]
Reminder to self: il branch compare magicamente in seguito ad una qualsiasi compilazione dei branch attivi.

**Comment by pdavide** [comment]
Sembra che si possa agire creando manualmente il webhook seguendo quanto riportato su: https://docs.readthedocs.io/en/latest/webhooks.html#webhook-creation

Sembra inoltre che i webhook creati automaticamente selezioni eventi diversi da quelli riportati nelle indicazioni sopra:
- webhook creati automaticamente: push + pull request
- webhook secondo le indicazioni: push + branch/tag creation/deletion (che mi sembra più corretto)

Da verificare se in upstream è stato fixato questo bug.

**Comment by Amanit** [comment]
Adesso i Webhook non erano creati automaticamente, ma era facile creare un Integrazione a mano.
Comunque non ho trovato nessun differenza tra i webhook creati da un Integrazione a mano o come erano creati automaticamente prima - sempre i eventi sono ['push', 'pull_request', 'create', 'delete'] (create/delete sono branch/tag create/delete).
Ho fatto un PR per farli creare automaticamente.
