### ISSUE TITLE
Nuovo branch non visibile

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#223]
## Dettagli

Ieri avevo creato un nuovo branch per il repo https://github.com/italia/design-linee-guida-docs.git, a cui corrisponde il progetto https://docs.italia.it/dashboard/design-linee-guida-docs/, ma non c'è modo di farlo comparire tra le versioni disponibili su Docs Italia e quindi di compilarlo e testarlo.

**Comment by francescozaia** [comment]
Reminder to self: il branch compare dopo un qualsiasi rebuild di una versione esistente

**Comment by yakky** [comment]
~~Dovrebbe essere collegata alla #222 ~~~ Non è collegata a quella issue

**Comment by Amanit** [comment]
@francescozaia Prima gli webhooks non seguivano i eventi di creazione/cancellazione di branch.
Ho creato un command per sincronizzare anche i vecchi webhooks.

**Comment by yakky** [comment]
@francescozaia il problema è risolto nella versione *già* in linea (risolto da upstream) ma gli webhook creati in precedenza sono ancora con gli eventi non aggiornati, quindi bisogna procedere ad aggiornarli tutti.

Il command nella PR collegata ci permetterà di lanciare l'update su tutti gli webhook già creati
