### ISSUE TITLE
La pagina di ricerca restituisce risultati relativi a versioni non pubbliche o disattivate

### ISSUE THREAD

**Issue by pdavide** [italia/docs.italia.it#235]
## Dettagli

* Pagina web del progetto su Docs Italia: https://docs.italia.it/search/?q=promozione&type=file

Dopo aver disattivato la versione "bozza" del documento `lg-comunicazione-docs`, i link nella pagina dei risultati della ricerca continuano a puntare verso la versione "bozza" causando un "Permission Denied" a chi vuole navigare verso quel documento.

**Comment by pdavide** [comment]
La SERP restituisce anche versione non esistenti di un documento, come ad esempio "bozza" per il documento "Codice dell'amministrazione digitale": https://docs.italia.it/search/?q=codice+amministrazione+digitale&type=file

**Comment by francescozaia** [comment]
È possibile che basti un reindex di ElasticSearch: https://github.com/italia/docs.italia.it/wiki/Indici-ES

**Comment by pdavide** [comment]
Ok faccio una prova e vediamo se il bug sparisce.

**Comment by pdavide** [comment]
Dopo aver reinizializzato ES mi sembra che le cose siano peggiorate.
La ricerca  "Codice dell'amministrazione digitale": https://docs.italia.it/search/?q=codice+amministrazione+digitale&type=file non restituisce il documento con lo stesso titolo.

**Comment by francescozaia** [comment]
Male. 😞 
Sembra proprio che quel documento non venga "visto" dalla ricerca; l'unica particolarità che mi viene in mente è il fatto che quel documento abbia varie versioni, ma nessuna `bozza`, che a questo punto sembra essere (temo) l'unica indicizzata. Ma la mia supposizione va ovviamente verificata!

**Comment by pdavide** [comment]
La tua supposizione mi sembra sensata nell'ottica RTD per la quale latest è l'ultima versione, non la bozza. Dovremmo impostare la generazione degli indici in modo da avere la stabile come versione predefinita e, se non esiste, la bozza. Se non esistono entrambe (caso CAD), l'ultima versione in ordine cronologico.

**Comment by pdavide** [comment]
Stando a quanto in https://github.com/italia/docs.italia.it/blob/italia-2.3.13/readthedocs/core/management/commands/reindex_elasticsearch.py#L33 dovrebbe indicizzare tutte le versioni attive di ciascun documento.

**Comment by pdavide** [comment]
Trovato l'inghippo! Il parametro `version` va in `bozza` di default. Non è quindi un problema di indicizzazione ma è relativo alla query di ricerca.
https://github.com/italia/docs.italia.it/blob/italia-2.3.13/readthedocs/search/views.py#L40

**Comment by francescozaia** [comment]
Collegato a #242 e #248
