### ISSUE TITLE
Verificare il link che appare nella home page

### ISSUE THREAD

**Issue by alterat** [italia/docs.italia.it#236]
## Dettagli

In alcune circostanze è possibile che nella home page di Docs Italia rimanga il link a una versione del documento anche se questa è stata disattivata. 

## Risultato che ci si aspettava

Quando una versione viene disattivata, sarebbe utile controllare i link presenti nella home page e aggiornarli, sostituendoli con la versione attiva.

**Comment by yakky** [comment]
@Amanit puoi verificare se questo è ancora un problema dopo il merge di #439 e #426?

**Comment by yakky** [comment]
Risolto da #451
