### ISSUE TITLE
Problemi con l'indicizzazione di pagine interne

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#239]
## Dettagli

Googlando _design scuole docs italia_ si arriva a link come
https://docs.italia.it/projects/design-scuole-docs/
https://docs.italia.it/projects/design-scuole-docs/builds/470/

## Risultato che ci si aspettava

Le pagine "interne" delle build e dei dettagli utente non dovrebbero essere indicizzate

**Comment by callmesangio** [comment]
@francescozaia Ciao, questa issue è ancora valida o è risolta? Ho visto che il file `robots.txt` è stato aggiornato a marzo di quest'anno.

**Comment by francescozaia** [comment]
Sì, l'avevo sistemata io. Nel frattempo però Google ha deprecato `noindex`, per cui si potrebbero togliere quelle 4 righe, lasciando solo:

```
User-agent: *
Disallow: /builds/
Disallow: /projects/
Disallow: /profiles/
Disallow: /sustainability/click/
```

(https://searchengineland.com/google-to-stop-supporting-noindex-directive-in-robots-txt-319003)
