### ISSUE TITLE
Change "Docs Italia Produzione" to "Docs Italia" in GitHub app name

### ISSUE THREAD

**Issue by alranel** [italia/docs.italia.it#241]
When performing the initial GitHub authentication, the name "Docs Italia Produzione" is displayed:

![screen shot 2019-02-17 at 20 20 22](https://user-images.githubusercontent.com/594957/52917983-b9f72600-32f1-11e9-9fa8-174a4c86ea2b.png)

I think this should be replaced by a simple "Docs Italia".

**Comment by francescozaia** [comment]
[Fixed](https://github.com/organizations/italia/settings/applications/866371), grazie
