### ISSUE TITLE
Il nome del progetto nell'URL è ignorato

### ISSUE THREAD

**Issue by alranel** [italia/docs.italia.it#244]
Prendendo un qualsiasi URL di un documento e sostituendo il progetto con una stringa casuale, il documento viene visualizzato ugualmente:

https://docs.italia.it/italia/foo/lg-acquisizione-e-riuso-software-per-pa-docs/it/bozza/

Questo è un comportamento tollerante che è sicuramente utile per mantenere vivi i link anche nel caso in cui un progetto venga rinominato. Mi aspetterei tuttavia che venga restituito un redirect 301 verso il nuovo URL, anziché servita direttamente la pagina (che rischia di essere anche indicizzata dai motori di ricerca). Il redirect è quanto fa ad esempio GitHub quando si rinomina un repository.

**Comment by callmesangio** [comment]
Fixed in #318
