### ISSUE TITLE
Il file PDF autogenerato presenta del problemi

### ISSUE THREAD

**Issue by danielelandro** [italia/docs.italia.it#245]
Il documento PDF che si genera a partire dai documenti RST presenti su docs italia nella sezione pagopa, per esempio [questo relativo alle SANP](https://docs.italia.it/italia/pagopa/pagopa-specifichepagamenti-docs/it/stabile/) ha degli errori di formattazione delle tabelle nelle versioni ad esempio, in Allegato A a pp. 6, 10 e 39; e in Allegato B un po' dappertutto.
[pagopa-specifichepagamenti-docs.pdf](https://github.com/italia/docs.italia.it/files/3178071/pagopa-specifichepagamenti-docs.pdf)

**Comment by alranel** [comment]
Un consiglio è il seguente:

> pulire un po' i sorgenti per vedere se ci sono miglioramenti. Ad esempio usando le direttive `figure` e `table` oppure facendo escape dei trattini che vedo dentro alcune tabelle (senza escape generano un `<li>`).

**Comment by danielelandro** [comment]
I documenti redatti, in particolare le SANP e SACI, presentano una struttura sintattica complessa, perché la tipologia di contenuti trattati è molto tecnica e sono necessarie tabelle, schematizzazioni grafiche e strutture annidate che non possono essere semplificate. In ogni caso il rendering dei file RST in HTML avviene correttamente, per cui dovrebbe avvenire allo stesso modo durante la conversione in PDF.
