### ISSUE TITLE
Il documento PDF autogenerato presenta la data di generazione e non quella di ultima modifica

### ISSUE THREAD

**Issue by danielelandro** [italia/docs.italia.it#246]
Il documento PDF che si genera a partire dai documenti RST presenti su docs italia nella sezione pagopa contiene la data di generazione del documento e non quella di ultima modifica del documento originale. Abbiamo ricevuto varie segnalazioni di utenti perchè questa data che cambia crea confusione in quanto viene interpretata come una nuova release, mentre invece è solo funzione del giorno in cui si stampa.

**Comment by alranel** [comment]
Aggiungo alla segnalazione che la data riportata nel frontespizio del documento PDF non sembra essere quella in cui si scarica il documento. Ad esempio scaricando oggi il PDF da https://docs.italia.it/italia/developers-italia/lg-acquisizione-e-riuso-software-per-pa-docs/it/stabile/ si ottiene "15 maggio 2019" che non è la data corrente né quella dell'ultimo commit. Forse è la data dell'ultima riconfigurazione del documento in Docs Italia?
