### ISSUE TITLE
[verificato su staging] La parola "stabile" dovrebbe essere "stable" per documenti in inglese

### ISSUE THREAD

**Issue by alranel** [italia/docs.italia.it#247]
Attualmente l'URL contiene la parola `stabile` anche se il documento è in lingua inglese. Per ottenere URL più adatti ad una audience internazionale sarebbe utile se venisse automaticamente utilizzata la parola `stable` quando la lingua del documento è diversa dall'italiano.

Esempio: https://docs.italia.it/italia/developers-italia/gl-acquisition-and-reuse-software-for-pa-docs/en/stabile/

**Comment by libremente** [comment]
A simple workaround could be to call a branch `stable` and leave only that one public

**Comment by francescozaia** [comment]
Se vado su https://old.dev.docs.italia.it/italia/developers-italia/gl-acquisition-and-reuse-software-for-pa-docs/ mi porta ancora su `stabile`.

**Comment by yakky** [comment]
@Amanit puoi verificare tu?

**Comment by francescozaia** [comment]
Questa issue è nice-to-have, se si rivela troppo complicata parliamone.

**Comment by yakky** [comment]
@francescozaia ok, la guardo con sergey
dai test ci sembrava funzionare (_it works on my computer_ ...) quindi c'è "solo" da capire perché su staging no, il codice è sicuramente allineatro

**Comment by Amanit** [comment]
@francescozaia mancavano i settings sul server.

**Comment by francescozaia** [comment]
Sembra ok, all'interno della tendina per la selezione della versione nel tema sphinx c'è scritto ancora "stabile", ma ce ne occuperemo in una issue separata.
