### ISSUE TITLE
Menu utente loggato in area back office

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#250]
## Dettagli
Conformare il menu dell'area back office per utenti loggati secondo quanto definito in questo documento:
https://docs.google.com/document/u/1/d/1Wa_8H5vjPprMfsn-p-OQHsMC1QEqAOLf65xoS1dDvRc/edit#heading=h.y255fe8z5ekz

Nota: molte di queste attività sono già state fatte, va completato il lavoro.

**Comment by francescozaia** [comment]
@SimoneNephila visto che il documento non è recentissimo e nel frattempo abbiamo aggiornato il nostro fork con la versione più recente di RTD, è possibile che ci siano discrepanze. Nel caso chiedi pure qui o su Slack, grazie

**Comment by yakky** [comment]
@francescozaia aggiornamento deployato
