### ISSUE TITLE
Aggiornamento alla versione più recente di ReadTheDocs

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#251]
## EPIC
Il completamento di questo epic comporterà una valutazione di fattibilità e  la creazione di una serie di issue per la lavorazione dell'attività in oggetto.

## Dettagli

Creare un nuovo branch basato sulla versione più recente di RTD (al momento 3.7 - noi siamo alla 2.3), in quanto vogliamo muoverci verso Python 3.6 ed ElasticSearch 6.
Eventuali conflitti su JS possono essere probabilmente risolti usando le nostre versioni. In particolare, si possono usare i nostri file per:

- README.rst
- readthedocs/builds/static/builds/js/detail.js
- readthedocs/core/static/core/js/autocomplete.js
- readthedocs/core/static/core/js/readthedocs-doc-embed.js
- readthedocs/core/static/core/js/site.js
- readthedocs/gold/static/gold/js/gold.js
- readthedocs/projects/static/projects/js/import.js
- readthedocs/projects/static/projects/js/tools.js

Verificare cosa fare per tutti gli altri conflitti.

Issue collegate:

- [x] #293 
- [x] #297
- [x] #298
- [x] #299 
- [x] #300
- [x] #301 
- [x] #302 
- [x] #303 
- [x] #304 
- [x] #305 
- [x] #306 
- [x] #322 
- [x] #355
- [x] #336
- [x] #332 
- [x] #326
- [x] #311 
- [x] #291 
- [x] #292

**Comment by francescozaia** [comment]
Attenzione che recentemente RTD ora è passato ad un modello con AD visibili a tema: https://blog.readthedocs.com/fixed-footer-ad-all-themes/

Verificare che questo non abbia impatti prima di procedere o sistemare questo comportamento nel nostro fork.

**Comment by francescozaia** [comment]
Lascio qui la scheda Trello relativa, in quanto ci sono un po' di informazioni che possono tornare utili: https://trello.com/c/bz1GKuY6/94-aggiornare-alla-pi%C3%B9-recente-versione-di-rtd

**Comment by xrmx** [comment]
Il mio consiglio quando si ribasa è droppare tutti i commit che riguardano la ricerca e rifarla da zero sopra alla nuova infrastruttura altrimenti non se ne esce :)

Un'altra cosa da droppare è l'analogo di questo:
https://github.com/readthedocs/readthedocs.org/pull/4356
che è stato risolto differentemente ma forse non completamente per lo use case di docs italia:
https://github.com/readthedocs/readthedocs.org/pull/5783#issuecomment-500899007
ma in caso il fix sarebbe diverso :)
