### ISSUE TITLE
Ricerca libera e filtrabile

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#252]
## Dettagli
Io come utente vorrei poter cercare dentro Docs Italia in modo libero con autocompletamento, anche filtrando per "publisher" e "per progetti" e "per tag", attraverso dei checkbox, come previsto dai layout di progetto:
https://invis.io/AQMX2Y2GTH2

Creare quindi le viste Django per i risultati della ricerca:
- Per ricerche dalla homepage, i risultati potranno essere filtrati per organizzazione e progetto
- Per ricerche dalla pagina di organizzazione, i risultati sono già ristretti a tale organizzazione e filtrabili per progetto

Per fare questo, è possibile ci sia una dipendenza dall'[aggiornamento di RTD](#251) che include ElasticSearch 6.

**Comment by filippo-20tab** [comment]
Rispondo in merito alle modifiche apportate di concerto con @pauloxnet:
- abbiamo pensato a un indice separato (con relativi documenti iscritti) per avere una singola ricerca dedicata e maggiore velocità possibile nell'indicizzare, nel cercare e nel riportare i dati (visto che i documenti non contengono tutti gli attributi, anche complessi degli altri indici); Paolo e Carmelo hanno effettivamente realizzato dei test usando gli indici esistenti e la velocità non gli è sembrata soddisfacente oltre a non funzionare per via di quanto descritto di seguito;
- l'analyzer full-text di ES è pensato per le esigenze di un motore di ricerca, quindi per valutare l'attinenza tra intere frasi cercate e lunghi testi, mentre in questa specifica ricerca il requisito è trovare con esattezza brevi quantità di caratteri dentro singoli titoli non molto lunghi, per questo l'analyzer attualmente implementato (i.e. "italian") non va bene (al meglio delle nostre conoscenze e test), per questo ci siamo affidati al meccanismo dei Trigram, con cui Paolo ha familiarità su Postgres, che permette di avere risultati anche con pochi caratteri cercati (es. restituisce correttamente i titoli contenenti "documento/i" se si digita "doc", cosa che nell'altro caso non avviene) e robustezza rispetto a semplici errori di digitazione.

Detto questo, sicuramente la ricerca può essere ulteriormente ottimizzata regolando i parametri del Trigram o scegliendo un analyzer differente, a tal proposito abbiamo fatto un buon numero di indagini e tentativi e non abbiamo trovato soluzioni migliori.

**Comment by yakky** [comment]
@filippo-20tab @pauloxnet :+1: grazie mille per l'ottima spiegazione, che ne dite di inserila come commento nel codice? cosi rimane a futura memoria

**Comment by pauloxnet** [comment]
@yakky ho aggiunto una docstring con il commento tradotto e reso impersonale partendo da quanto scritto in questa issue.

Se puoi procedi a fare review e nel caso a mergiare la PR.

**Comment by pdavide** [comment]
Non so se è questa la issue giusta per segnalare che, rispetto ad alcune chiavi di ricerca, appaiono dei risultati relativi a pagine che non hanno il titolo. Dato che sono perfettamente inutili come risultati, direi di escluderli dalla visualizzazione.

D'altro canto si potrebbe impostare sphinx, se fosse possibile, in modo da far fallire le build nel caso di pagine senza titolo (da valutare in altra issue).

<img width="982" alt="Schermata 2019-12-21 alle 18 35 05" src="https://user-images.githubusercontent.com/9119858/71311664-36cac300-2421-11ea-8aec-c356a6c18631.png">

**Comment by yakky** [comment]
@pdavide riapro, direi che è la issue giusta
@filippo-20tab immagino sia da fare qualche filtro qui https://github.com/italia/docs.italia.it/pull/435/files#diff-bd1c1d813adf845b85ad11cd35e42220R33
