### ISSUE TITLE
Ricerca: Filtri per "progetto" e "tag"

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#256]
## Dettagli
Io come utente vorrei poter cercare dentro Docs Italia in modo libero e anche filtrando "per progetti" e "per tag", attraverso dei checkbox come da layout di progetto:
https://invis.io/AQMX2Y2GTH2

Correlata a #252 e #255

**Comment by pauloxnet** [comment]
Nell'ordinamento sostituire la label di default "Popolarità" con "Rilevanza".
