### ISSUE TITLE
Gestione tag ammessi per i documenti

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#257]
## Dettagli
Partendo da questo documento/vocabolario controllato: https://docs.google.com/spreadsheets/d/1o6PUd4ba8sjhiv2xid98NVkEt5va1JF9lkNwUuHhla4/edit?usp=sharing (da validare con Matteo Troìa).

Creare un sistema che limiti i tag utilizzabili a quelli definiti all'interno di una lista (modificabile con relativa semplicità da Django admin o simile), in modo che tale lista possa essere curata a mano su Docs Italia che fa da "filtro" per evitare che qualsiasi tag custom possa essere aggiunto.

A livello di documento, verificare se i tag sono al momento nel file di configurazione yaml o inseriti da backoffice. Nel primo caso:
- Vantaggi: per i publisher sarà facile da gestire e mantenere, nessun editing nel back office di RTD/DocsItalia.
- Svantaggi: non c'è validazione se l'utente modifica direttamente da GitHub e non da Docs Italia. Essendo i tag non regolamentati, ci apriamo a proliferazione di tag, errori ortografici, ecc. 

Da discutere che fare del box tags nel back office di RTD, e fare in modo che nel caso ripulisca maiuscole, spacing, etc.

**Comment by callmesangio** [comment]
@francescozaia Ciao, nel caso in cui compaiano dei tag non ammessi all'interno di `document_settings.yml` come vogliamo comportarci? Sistemiamo implicitamente la lista togliendo quelli non in whitelist oppure dobbiamo bloccare la build e notificare l'errore all'utente?

Grazie!

**Comment by francescozaia** [comment]
Scusami @sanjioh ero impegnato, ne avevo parlato brevemente con @yakky e spero tu abbia già risolto. Ad ogni modo, non bloccherei la build e eliminerei il tag in modo silenzioso. Se riusciamo in qualche modo a notificarlo con un warning, tanto meglio. Appena posso vedo la PR, grazie

**Comment by callmesangio** [comment]
Ciao, ero partito anche io con l'eliminazione silenziosa dei tag non ammessi, quindi la PR attuale riflette già questo comportamento. La PR è ancora DRAFT perché manca la parte frontend (limitazione agli allowed tags nella selezione lato backoffice), che è in progress.

**Comment by callmesangio** [comment]
È necessario impedire che il widget di scelta tag (nel backoffice) consenta l'inserimento di nuovi tag (la feature riguarda solo il frontend, lato backend i tag non validi vengono filtrati).
La PR richiede competenze frontend per essere ultimata.

**Comment by carmelocatalfamo** [comment]
Ho provato a lavorarci per un po ma in questo momento sono bloccato.

L'obiettivo era bloccare la "select" per prevenire l'inserimento da parte degli utenti di nuovi tag.
Per farlo mi sono messo in ascolto [dell'evento](https://django-autocomplete-light.readthedocs.io/en/master/tutorial.html#overriding-javascript-code) che inizializza select2 `autocompleteLightInitialize`.

Il problema è che questo evento sembra non essere mai chiamato e select2 risulta `undefined` anche se i files statici sono presenti nella pagina.

```html
<script type="text/javascript">
  $(document).on('autocompleteLightInitialize', '[data-autocomplete-light-function=select2]', function () {
    // Customize select2
  })
</script>
```

**Prove effettuate**
- aggiungere `{{ form.media }}` nel template (che include i files statici).
- modificate le `INSTALLED_APPS` spostando `dal` e `dal_select2` prima di `django.contrib.admin`
- trigger invato manualmente (ma select2 risulta `undefined` nonostante sia presente tra i links)

**Note**
- Se alla `riga 216` del file `/readthedocs/projects/form.py` aggiungo l'opzione `autocomplete_function = "project_tags"` il plugin "si rompe"

___

File `/readthedocs/templates/docsitalia/overrides/projects/project_edit.html`
```html
{% extends "projects/project_edit_base.html" %}
{% load i18n %}

{% block project-edit-active %}active{% endblock %}
{% block nav-dashboard %} class="active"{% endblock %}

{% block title %}{% trans "Edit Project" %}{% endblock %}

{% block editing-option-edit-proj %}class="active"{% endblock %}
{% block editing-option-view %}active{% endblock %}

{% block project_edit_content_header %}{% trans "Settings" %}{% endblock %}

{% block project_edit_content %}
  <form method="post" action=".">{% csrf_token %}
    <div class="form-container">
      {{ form.as_p }}
    </div>
    <p>
      <input class="btn btn-primary" type="submit" value="{% trans "Save" %}">
      {% comment %}Translators: The 'or' here is in between 'Save' and 'Delete project'.{% endcomment %}
      {% trans "or" %}
       <a class="btn btn-secondary" href="{% url "projects_delete" project.slug %}">{% trans "Delete project" %}</a>
    </p>
  </form>
{% endblock %}

{% block extra_scripts %}
{{ form.media }}
<script type="text/javascript">
  $(document).on('autocompleteLightInitialize', '[data-autocomplete-light-function=select2]', function () {
    console.log('$(this).select2', $(this).select2)
  })

  // Manual trigger
  // $(document).ready(function () {
  //   var select = $('[data-autocomplete-light-function=select2]')
  //   select.trigger('autocompleteLightInitialize')
  // })
</script>
{% endblock %}
```

**Comment by callmesangio** [comment]
I problemi lato frontend sono stati risolti configurando Select2 via backend (https://github.com/italia/docs.italia.it/pull/282/commits/30627c61b924f411b138ccb63ea37e17e3f77f6b).
La modifica non trova riscontro nella documentazione di `django-autocomplete-light`, ma risulta efficace e produce il risultato desiderato.
