### ISSUE TITLE
Implementare il filtro dei risultati di ricerca per popolarità

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#259]
## Dettagli
È possibile introdurre un filtro/ordinamento per i documenti più visti o popolari? Da investigare e nel caso definire come lavorarci.

**Comment by pauloxnet** [comment]
Si è deciso di sfruttare il valore di priorità introdotto nella PR #426 per effettuare un ordinamento della ricerca in base a questo valore ed in caso di mancanza di questo valore nell'indice di ES di usare la rilevanza assegnata da ES al documento nella ricerca.

Questa issue rimane bloccata solo fino al merge della PR #426
