### ISSUE TITLE
Gestione pagine 404, unauthorised, ed altri errori

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#262]
## Dettagli
Verificare che le pagine di errore (o non accessibili per problemi di permessi) spieghino che sta succedendo in italiano e permettano almeno di tornare alla homepage agevolmente.
Es:
- documento inaccessibile: https://docs.italia.it/docs/pagopa-portaledelleadesioni-docs/it/bozza/index.html?highlight=docs
- documento invalido: https://docs.italia.it/docs/dasdasdasd/
- 404: https://docs.italia.it/joasjdpiajdps

**Comment by pauloxnet** [comment]
Queste sono le pagine che vengono visualizzate per gli errori
# 401
![401 local docs italia it](https://user-images.githubusercontent.com/521097/65155377-77cfc780-da2d-11e9-991f-58f808659d61.png)
# 404
![404 local docs italia it](https://user-images.githubusercontent.com/521097/65155378-77cfc780-da2d-11e9-817f-9323549a2a74.png)
# 500
![500 local docs italia it](https://user-images.githubusercontent.com/521097/65155379-77cfc780-da2d-11e9-905c-cb2c2cad5f10.png)

**Comment by yakky** [comment]
Per la 404 segnalo questa #141 

Non sono sicuro che tutte le 404 si riescano a far gestire da nginx o se sia il caso di sistemarle e farle gestire comunque a django

**Comment by pauloxnet** [comment]
@yakky ci sono in effetti alcuni erroi 404 intercettai direttamente da nginx e che credo saranno da gestire nella issue #141 creando una pagina statica.

@francescozaia non avendo specifiche del testo da inserire nelle pagine di errore ho adattato dei testi di altri progetti del team digitale ed ho aggiornato i template esistenti con il risultato di seguito (codice nall PR #285)

# 401

![401](https://user-images.githubusercontent.com/521097/65319101-29423a80-db9f-11e9-8b11-673a64e0092e.png)

# 404

![404](https://user-images.githubusercontent.com/521097/65319118-34956600-db9f-11e9-99a5-58f1edb7895b.png)

# 500

![500](https://user-images.githubusercontent.com/521097/65319130-3bbc7400-db9f-11e9-9ff5-c80a7c5441bd.png)

**Comment by yakky** [comment]
@SimoneNephila verifchi che anche il lavoro sulla pagina statica sia allineato in termini di template? Tu stavi lavorando con il design dello ui kit ufficiale, giusto?
Farei in modo di tenere tutto allineato
Semmai facciamo il merge di #285 e poi una di allineamento di tutti i template

**Comment by yakky** [comment]
riassegno a me, qui potrebbe essere qualche problema nella configurazione nginx lato italia/docs-italia-deploy-scripts

**Comment by yakky** [comment]
@francescozaia questo apparentemente è andato perso nell'upgrade di versione
È sufficiente fare il porting di #285

**Comment by yakky** [comment]
Qui il fix per la 404 gestita da nginx https://github.com/italia/docs-italia-deploy-scripts/pull/91

**Comment by yakky** [comment]
@pdavide @francescozaia fatto il deployment dell'aggiornamento

**Comment by pdavide** [comment]
Verificato OK.
