### ISSUE TITLE
Convertitore non funzionante

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#264]
## Dettagli
Ho ricevuto segnalazione che il [convertitore](https://docs.italia.it/converti/) non sta funzionando a dovere, da verificare.

**Comment by callmesangio** [comment]
@francescozaia Ciao, abbiamo qualche dettaglio in più su quali siano i problemi riportati? Grazie mille

**Comment by francescozaia** [comment]
@sanjioh avevamo ricevuto segnalazione che non funzionasse del tutto. In realtà ho appena verificato e invece sembra ok, bug di conversione esclusi (che però non sono oggetto di questa issue). Chiudo, in attesa di avere modo, nel prossimo futuro, di loggare meglio eventuali malfunzionamenti.
Grazie
