### ISSUE TITLE
Automazione rinnovo certificati

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#267]
## Dettagli
Al momento stiamo rinnovando i certificati a mano con `certbot renew` (e, ogni tanto con qualche clashing su nginx durante la challenge). Sarebbe bello automatizzare il rinnovo dei certificati.

**Comment by yakky** [comment]
Questo può essere superato dall'uso di kubernetes (vedi #261) se non è urgentissimo (l'obiettivo è avere il deploy su kubernetes entro il primo sprint ma lo spostamento della produzione su kubernetes potrebbe essere un po' più lungo)

**Comment by francescozaia** [comment]
Assolutamente non urgente, per cui procediamo pure contestualmente a #261.
