### ISSUE TITLE
Possibilità di avere dipendenze di parentela tra i documenti

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#269]
## Dettagli
Io come funzionario vorrei poter costruire un **box con tutti i documenti che hanno un rapporto di dipendenza con un documento di progetto**.

Questo perché, da eventi di formazione fatti in AGID, è emerso che esistono "grappoli" di documenti che, sebbene siano burocraticamente indipendenti, semanticamente non lo sono.
Esempio:
http://www.agid.gov.it/sites/default/files/documentazione/spid-avviso-n3-chiarimenti-sessioni-singlelogout.pdf
dipende da
http://www.agid.gov.it/sites/default/files/circolari/spid-regole_tecniche_v1.pdf

Per questo motivo pensavamo di dare all'utente la possibilità di visualizzare quali documenti dipendono dal documento corrente o se il documento corrente dipende da altri documenti.

Per realizzare questa feature potrebbe essere utile:
- sfruttare le già esistenti [relazioni project/subproject](https://docs.readthedocs.io/en/latest/subprojects.html) che ci sono in ReadTheDocs, con eventuali implicazioni serie a livello di URL (che, se implementato come su ReadTheDocs potrebbe diventare qualcosa del genere: https://docs.italia.it/nome_publisher/nome_progetto/super_documento/sub_documento/) e funzionamento, da verificare;
- creare ex novo una modalità di relazioni unidirezionali (da uno a molti) "manualmente" dentro un documento con dei tag/metadati particolari.

**Comment by yakky** [comment]
@francescozaia da tenere presente che RTD già gestisce i sottoprogetti https://docs.readthedocs.io/en/stable/subprojects.html
Da verificare se utili allo scopo
Il link alla sezione relativa è attualmente commentato (volutamente)

**Comment by Amanit** [comment]
gia e' scommentato questo link. Si puo vedere/cambiare i sottoprogetti.
