### ISSUE TITLE
Riscrittura URL dopo modifica nomi di file

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#272]
## Dettagli
Con riferimento a https://github.com/italia/lg-acquisizione-e-riuso-software-per-pa-docs/issues/51, dovremmo fare in modo che alcuni URL pubblici continuino a linkare pagine che verranno rinominate. È una cosa one-time, per cui presumo che la soluzione più rapida sia quella di aggiungere qualche regola a livello di nginx.

**Comment by yakky** [comment]
Nessun problema basta modificare questo file https://github.com/italia/docs-italia-deploy-scripts/blob/master/roles/app/templates/nginx/snippets/docs-redirects.conf e rifare il deployment

**Comment by francescozaia** [comment]
Comunicato ai ragazzi di aggiornare il file, attendiamo loro PR.

**Comment by francescozaia** [comment]
Loro hanno pubblicato online, anche la nostra PR è mergiata (https://github.com/italia/docs-italia-deploy-scripts/pull/84) ora dobbiamo solo fare una pubblicazione live per aggiungere il nuovo script.
