### ISSUE TITLE
Gestione dei secret nella containerizzazione

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#276]
## Dettagli

Aggiungere gestione dei secret alla #271

**Comment by pauloxnet** [comment]
Aggiunta gestione dei secrets in 747aa43901665b7c05ed6407b3794d00546fea85 con documentazione nella pagina wiki [Setup dell'ambiente di sviluppo locale](https://github.com/italia/docs.italia.it/wiki/%5BDRAFT%5D-Setup-dell'ambiente-di-sviluppo-locale)
