### ISSUE TITLE
Inizializzazione elastic search

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#277]
## Dettagli

Quando si parte da un volume vuoto è necessario inizializzare il container con bin/elasticsearch-plugin install analysis-icu

è necessario automatizzarlo in modo che venga eseguito durante la build del container

Vedi #271

**Comment by callmesangio** [comment]
Questo commit dovrebbe risolvere la issue:
https://github.com/italia/docs.italia.it/commit/091d3e8d00b88c633c04779531b9f0e95f05df0d
Documentazione: https://github.com/italia/docs.italia.it/wiki/%5BDRAFT%5D-Setup-dell'ambiente-di-sviluppo-locale

**Comment by callmesangio** [comment]
Aggiunta provisioning ES all'avvio dei container web/api.
https://github.com/italia/docs.italia.it/commit/7075376a86dd2480f4dddb4a47c0e7bb26033a9e
