### ISSUE TITLE
Analisi diff rtd-2.3.13 / rtd-master

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#291]
Analizzare le differenze fra rtd 2.3.13 e rtd 3.7.4 per verificare aree più pesantemente modificate.
Da comparare con l'output di #292 per capire le aree più critiche

**Comment by callmesangio** [comment]
Ciao, ho pensato ad un metodo per ottenere con precisione i file interessati da modifiche bloccanti rispetto all'avanzamento di versione del fork.

Vi chiederei una validazione per capire se la procedura è corretta:

1. nel repository `readthedocs.org`, branch `master`, eseguire:
`git diff --name-only 2.3.13 3.7.4 > rtd_diff_2.3.13_3.7.4.txt`
In questo modo otteniamo tutti i file interessati dai commit tra i due tag di release.

2. nel repository `docs.italia.it`, branch `italia-2.3.13`, eseguire:
`git diff --name-only 076539117 > di_diff_2.3.13_HEAD.txt`
In questo modo otteniamo tutti i file interessati dai commit tra la release della versione 2.3.13 (in questo caso usiamo lo sha perché su docsitalia non c'è tag) e l'attuale HEAD.

3. lanciamo questo script che estrae i file comuni ai due diff:
```python
RTD = '/path/to/readthedocs.org/rtd_diff_2.3.13_3.7.4.txt'
DI = '/path/to/docs.italia.it/di_diff_2.3.13_HEAD.txt'

with open(RTD, 'r') as rtd:
    rtd_paths = set(rtd)

with open(DI, 'r') as di:
    di_paths = set(di)

common_paths = sorted(list(rtd_paths & di_paths))

for path in common_paths:
    print(path, end='')
print('\nTotal: {} files'.format(len(common_paths)))
```

@yakky @pauloxnet @Amanit cosa ne pensate? Grazie!

**Comment by pauloxnet** [comment]
Ho verificato che il flusso descritto funziona ed è utile per avere l'elenco dei file comune ai due diff.

**Comment by francescozaia** [comment]
So che preferite fare tutto da command line, ma anche se avete IDE JetBrains qualcosa si può ottenere:
<img width="1440" alt="Screenshot 2019-09-25 at 12 20 41" src="https://user-images.githubusercontent.com/481084/65592473-e7ded000-df8e-11e9-90c3-7844bdb4ea3d.png">

**Comment by yakky** [comment]
per la mia parte sto analizzando il merito della diff, ho paura che i soli file dicano poco, perché probabilmente avremo modificato l'80% dei file, ma alcuni con modifiche minime e senza impatto reale
perô se intanto vi torna comodo partire dall'elenco dei file ok
vi ricordo però che si è detto di analizzare separatamente le modifiche fatte *su* RTD e quelle fra RTD e docs.italia (#292 ) di cui mi sto occupando io

**Comment by callmesangio** [comment]
Certo, l'elenco serve come base per riuscire a concentrare il focus sulle modifiche che hanno impatto sul fork. Da parte mia resta confermato il mantenere separate le due attività come discusso in call.

**Comment by yakky** [comment]
:+1:
