### ISSUE TITLE
Reimplementazione API REST

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#300]
Le modifiche attualmente su `restapi` verso API v3

**Comment by callmesangio** [comment]
Ho fatto un'analisi di cosa fosse stato modificato nella directory `readthedocs/restapi` sul branch `italia-2.3.13`, e riportato quanto scoperto nel seguente documento: https://docs.google.com/document/d/1jlxlyRCQ-f-plU437XKFvkgMfltDlOK8PyfxdKOtYzU/

In sintesi, dall'analisi non si ha evidenza di modifiche fatte a docsitalia in questo ambito (fatta eccezione della funzionalità di ricerca, oggetto della issue https://github.com/italia/docs.italia.it/issues/301) che debbano essere portate alle API v3 di RTD per non perdere funzionalità.

**Comment by callmesangio** [comment]
@yakky @francescozaia Ho messo la issue un `review in progress` perché mi sembra lo step logico successivo più corretto, anche se non ha una PR associata.
