### ISSUE TITLE
Reimplementazione ricerca

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#301]
- [x] Aggiornare gestione indice (search/indexes)
- [x] Logica di ricerca (`search/libs` `search/views`)
- [x] ~~vendoring del comando personalizzato `reindex_elasticsearch`~~

al di là di publisher / publisherproject ci sono questi altri elementi di personalizzazione da riportare alla nuova versione:

- ~~analyzer custom https://github.com/readthedocs/readthedocs.org/compare/2.3.13...italia:italia-2.3.13#diff-4c298e759d2763548bb080a73fd4611eR77~~ -> #326
- minimum scoring https://github.com/readthedocs/readthedocs.org/compare/2.3.13...italia:italia-2.3.13#diff-e2489802fffb649a400de413291102fdR80
- ~~escludere i progetto privati https://github.com/readthedocs/readthedocs.org/compare/2.3.13...italia:italia-2.3.13#diff-e2489802fffb649a400de413291102fdR174~~
- ~~tipo di ricerca di default https://github.com/readthedocs/readthedocs.org/compare/2.3.13...italia:italia-2.3.13#diff-8880719d5229984479b4d241fe0efd3eR38~~
- ~~visualizzazione campi https://github.com/readthedocs/readthedocs.org/compare/2.3.13...italia:italia-2.3.13#diff-8880719d5229984479b4d241fe0efd3eR68~~

**Comment by yakky** [comment]
@francescozaia ti segnalo una piccola modifica nel comportamento standard di RTD rispetto all'attuale.

In italia-2.3.13 facendo una ricerca (https://docs.italia.it/search/?q=lorem) compare la lista di amministrazioni e progetti a sx. Selezionando un'amministrazione (o un progetto) la ricerca viene filtrata e le altre voci dello stesso tipo scompaiono (es: https://docs.italia.it/search/?q=lorem&publisher=italia)

Nella versione aggiornata il comportamento di default è che il facet selezionato viene evidenziato ma gli altri elementi dello stesso tipo rimangono visibili (ciascuno con il relativo numero di risultati che comparirebbe se venisse selezionato) e selezionabili cosi da poter switchare fra i diversi valori dello stesso facet.

Reimplementiamo il comportamento di italia-2.3.13 o ci piace quello nuovo (almeno per il momento)?

**Comment by francescozaia** [comment]
Scusate il ritardo nella risposta, ci va benissimo quello nuovo! Thanks for asking :)

**Comment by yakky** [comment]
questa direi di chiuderla, ci siamo segnati le cose da gestire separatamente
