### ISSUE TITLE
Verifica customizzazione ProjectDetailView

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#304]
Verificare se in `ProjectDetailView.get_context_data` è necessario l'uso di `PUBLIC_PROTO` al posto di `request.is_secure` come fa upstream

Verificare rispetto alla PR di Riccardo che lo introduce

**Comment by callmesangio** [comment]
Ho fatto dei test abilitando l’https in nginx, con relativo forward a django di `X-Forwarded-Proto` per avere riscontro su `request.is_secure()`.
Ne risulta che non è necessario usare `PUBLIC_PROTO`, premesso che ci vada bene legare il protocollo dell’url del badge a quello della request.

Legando invece lo scheme a `PUBLIC_PROTO` si ha un unico punto centralizzato per la determinazione dello scheme nella risoluzione degli URL, che è condiviso anche dal `Resolver` custom.

**Comment by yakky** [comment]
Secondo me si, ha senso. comunque i badge sono gestiti dall'infrastruttura standard. quindi qusta si potrebbe chiudere e droppare il commit

**Comment by callmesangio** [comment]
D'accordo.
Va bene se facciamo un commit con il fix (o un commit di revert), così tracciamo in una PR dedicata?

**Comment by yakky** [comment]
secondo me possiamo droppare silenziosamente il commit
