### ISSUE TITLE
Documentare decisioni prese durante l'upgrade a master

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#311]
## Dettagli

È necessario documentare le decisioni (macro e micro) prese durante l'upgrade in un documento

In particolare:

* Metodologia di porting (copia del codice anziché merge)
* Fasi di porting (ovvero: porting di tutto tranne la ricerca, uso della v2 delle API, porting ricerca, upgrade a API v3)
* Commit / funzionalità non portate alla nuova versione (indicare eventuali parti del codice, issue di porting con relativo commento, PR originale che introduceva la funzionalità)

**Comment by callmesangio** [comment]
Ho creato il documento con le informazioni relative alle issue di mia competenza: https://github.com/italia/docs.italia.it/wiki/%5BWIP%5D-Porting-a-RTD-3.7.x---scelte-tecniche

**Comment by yakky** [comment]
@francescozaia https://github.com/italia/docs.italia.it/wiki/Porting-di-RTD-da-2.3.13-a-3.7.x---scelte-tecniche :sweat_smile:

**Comment by francescozaia** [comment]
Ottimo lavoro, ho sistemato un pochino la formattazione mentre lo rivedevo, ma nulla di che.
