### ISSUE TITLE
Preimpostazione della UI per il layer di ricerca

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#314]
## Dettagli
Con riferimento alla [sezione Design](https://github.com/italia/docs.italia.it/wiki#design) della Wiki, e in particolare al [documento riepilogativo sul funzionamento della ricerca](https://docs.google.com/presentation/d/1_oV7oU9cE6t013iUg6PdMbQeQ214hTTd2wJMiCLb4-4/edit), potremmo provare ad iniziare ad impostare il frontend (con quello che abbiamo, senza ElasticSearch) con il layer visibile a pagg.5/6 del documento.

Non potendo ancora fare tutto non so che valore possa avere, però se pensate possa tornare utile per "portarci avanti", magari ci si può lavorare, almeno in termini di CSS e JS.

Alcuni riferimenti che magari possono essere utili (cliccare il tasto "cerca" a destra in testata):
- https://beta.comune.cagliari.it/ponmetroca/
- https://developers.italia.it/
- https://www.comune.ala.tn.it/

**Comment by carmelocatalfamo** [comment]
Questa si può chiudere.
Tutto il lavoro di pre-impostazione della ricerca alla fine è stato spostato sul branch `feature/363-ricerca`

**Comment by yakky** [comment]
Chiudo, rimane attivo nella board di testing

**Comment by francescozaia** [comment]
Verificata la parte di stile/UI, tutto ok. C'è un problema con il menu su IE11, ma vista la poca utenza di tale browser, aggiungo https://github.com/italia/docs.italia.it/issues/455.
