### ISSUE TITLE
Prevenzioni di abusi nella pubblicazione

### ISSUE THREAD

**Issue by alterat** [italia/docs.italia.it#32]
## Details

Supponiamo che l'organizzazione su GitHub _Acme_ sia autorizzata su Docs Italia. 
Tutti i repo di Acme diventano a quel punto automaticamente pubblicabili su Docs Italia. 
È possibile prevenire la pubblicazione di un documento da parte di Acme, qualora questo non abbia le caratteristiche per stare su Docs Italia?

## Expected Result

Vorrei che ci fosse un meccanismo di controllo dei documenti pubblicati che serva non da barriera a monte, ma che permetta di "spubblicare" eventuali documenti non consoni alla piattaforma. È previsto? In caso contrario, parliamone :)

**Comment by yakky** [comment]
Dalla dashboard (o dall'admin) è possible cambiare il livello di privacy a "private" e quindi nasconderli
Non esiste però un vero di meccanismo di moderazione (quindi con livelli diversi fra gli utenti), per cui chiunque abbia accesso al progetto in questione può modificarlo e ripubblicarlo

**Comment by alterat** [comment]
Grazie @yakky!

Quindi, se ho capito bene, la politica in caso di abusi sarebbe:
1. rimprovero bonario da parte degli admin all'utente/organizzazione che si comporta male
2. nel caso il rimprovero non venga ascoltato, ban all'intera organizzazione e rimozione di tutti i documenti

Per rimuovere un eventuale documento non conforme, l'unico metodo davvero efficace sarebbe revocare i privilegi all'organizzazione e a tutti i suoi documenti, giusto?

**Comment by yakky** [comment]
@atorin esatto. attualmente direi che è il flusso già presente a "costo zero"
Chiedo comunque conferma a @xrmx che conosce meglio di me questa parte
Nulla osta ad avere politiche più raffinate, soprattutto a livello di publisher / progetto, perché sono oggetti completamente gestiti dal nostro fork
Più complicato lavorare sul singolo documento

**Comment by xrmx** [comment]
Si se disattiviamo una organizzazione i progetti e documenti non si vedranno nel sito e con un comando possiamo rimuovere tutte le build delle documentazione dall'indice della ricerca.

**Comment by yakky** [comment]
@francescozaia questa è ancora rilevante?

**Comment by francescozaia** [comment]
No, si può chiudere. Sicuramente per ora possiamo tranquillamente gestire eventuali problemi dall'area amministrativa del sito.
