### ISSUE TITLE
Indirizzare i tracciamenti di errori ed eventi sensibili su Azure

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#321]
## Dettagli
Finora abbiamo usato Sentry per tracciare errori su produzione; a breve dovremmo spostare tutto su Azure. Dovremmo quindi prepararci all'utilizzo del Monitoring sul portale Azure indirizzando i nostri log adeguatamente.
Penso questo possa essere un buon punto di partenza:
https://docs.microsoft.com/it-it/azure/azure-monitor/app/opencensus-python

**Comment by yakky** [comment]
Insights sembra più orientato alle metriche e ai log più che agli errori e la documentazione per l'integrazione con django non è delle più chiare (https://pypi.org/project/opencensus-ext-django/) ma probabilmente studiandolo un po' gliela si fa :)

@LucaPrete tu hai altri suggerimenti in merito?

**Comment by LucaPrete** [comment]
Iacopo,

Qual'è esattamente il caso d'uso? Tieni presente che tutti i log dei
container sono automaticamente raccolti attraverso log analytics.

-Luca

Il giorno mar 5 nov 2019 alle ore 22:11 Iacopo Spalletti <
notifications@github.com> ha scritto:

**Comment by yakky** [comment]
> Iacopo, Qual'è esattamente il caso d'uso? Tieni presente che tutti i log dei container sono automaticamente raccolti attraverso log analytics.

Intercettare gli errori a livello applicativo ed averli in una modalità strutturata e navigabile che permetta di accedere al traceback e a tutta una serie di informazioni a runtime @francescozaia fors esi può dare con Luca un'occhiata a Sentry così mi spiego meglio
