### ISSUE TITLE
Aggiornamento / Fix template aggiornamento

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#322]
## Dettagli

È necessario aggiornare alcuni template e alcuni elementi frontend per completare l'aggiornamento

* [x] Template pagina risultati di ricerca non visualizza i dati (compare una card vuota). Dipende sicuramente dal rename degli attributi nelle nuove versioni di elastic
* [x] sprite.svg dà un 404
* [x] CSS mancanti nella pagina di informazioni sulle build

**Comment by carmelocatalfamo** [comment]
Il primo punto è stato corretto da @filippo-20tab e @daniele20tab direttamente sul branch `feature/issue-301-italia-search`
