### ISSUE TITLE
[verificato su staging] Riferimento errato a file manifest e contenuti da verificare

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#323]
## Dettagli
Il sito cerca [un file `manifest.webmanifest`](https://docs.italia.it/media/docsitalia/icons/manifest.webmanifest) che non è presente:

<img width="583" alt="Screenshot 2019-10-22 at 14 40 06" src="https://user-images.githubusercontent.com/481084/67286534-dc24f180-f4d9-11e9-9b26-a41c2475922c.png">

È presente invece un [file JSON](https://github.com/italia/docs.italia.it/blob/italia-2.3.13/media/docsitalia/icons/manifest.json) che si può rinominare ed, in parte, riutilizzare. Qui la specifica W3C:
https://www.w3.org/TR/appmanifest/
(occhio all'estensione `.webmanifest` che magari può dare problemi di mime-type)

Per quanto riguarda le immagini da usare, si può fare riferimento all'attuale cartella delle icone ed aggiungere eventuali misure necessarie; per lo screenshot si può usare questa:

![docs-italia-1280](https://user-images.githubusercontent.com/481084/67287307-22c71b80-f4db-11e9-86ff-76a86a3cb5cd.png)

**Comment by francescozaia** [comment]
Il file manifest al momento presente su Staging è un JSON non valido (segnalato quindi come errore in console da Chrome). Ne riporto il contenuto:
```
---
# keep this !
---
{
    "name": "it",
    "icons": [
        { ... },
        { ... }
    ],
    "theme_color": "{{ site.theme_color }}",
    "background_color": "{{ site.theme_color }}",
    "display": "standalone"
}
```
A mio avviso va:
- rimossa l'intestazione YAML-style:
```
---
# keep this !
---
```
- sistemati i due `{{ site.theme_color }}` (si può anche hardcodare `#0066CC`, non è grave)

**Comment by yakky** [comment]
@francescozaia aggiornamento deployato
