### ISSUE TITLE
Verifica uso analyzer / filter

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#326]
## Dettagli

È necessario verificare se sulla nuova ricerca sia ancora necessario usare questo codice custom
https://github.com/readthedocs/readthedocs.org/compare/2.3.13...italia:italia-2.3.13#diff-4c298e759d2763548bb080a73fd4611eR77 a fronte del drop di analyzer-icu fatto da RTD

**Comment by pauloxnet** [comment]
Verificare come e dove impostare l'analyzer italiano

**Comment by pauloxnet** [comment]
Il fix all'analyzer mergiato non sta funzioanando.

L'unica soluzione testata che effettivamente mi permette di indicizzare il testo con l'analyzer italiano è quello descritto nel mio commento alla PR.

https://github.com/italia/docs.italia.it/pull/395#issuecomment-555073133
