### ISSUE TITLE
Verifica traduzioni in template pagina build

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#329]
Verificare traduzioni italiane in https://github.com/italia/docs.italia.it/blob/feature/issue-293-upgrade/readthedocs/templates/docsitalia/overrides/builds/build_detail.html

Ci sono delle stringhe in inglese ma vedo che sono comprese in blocchi `{% blocktrans trimmed %} ... {% endblocktrans %}`

_Originally posted by @francescozaia in https://github.com/italia/docs.italia.it/pull/324_

**Comment by carmelocatalfamo** [comment]
Quasi tutte le traduzioni della pagina funzionano,
ad esempio questo nodo
```django
<li>
  {% trans "Completed" %}
  <span>{{ build.date|date:"N j, Y. P" }}</span>
</li>
```
Si traduce in
```html
<li>
  Completato
  <span>28 Ott. 2019 10:52 a.m.</span>
</li>
```

Quelle più complesse invece sembrano non funzionare (anche in staging), forse non sono tradotte.
Vedi:

<img width="919" alt="translate" src="https://user-images.githubusercontent.com/11672358/68119108-1642ba00-ff02-11e9-81c7-a2b8fee1bd64.png">

Come ci comportiamo?

**Comment by francescozaia** [comment]
Andrebbe capito dov'è il file di traduzioni e aggiornarlo con quello scaricabile da Transifex, però penso si possa gestire nella issue dedicata: https://github.com/italia/docs.italia.it/issues/328.
