### ISSUE TITLE
Verifica presenza knockout.js in template pagina build

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#331]
In https://github.com/italia/docs.italia.it/blob/feature/issue-293-upgrade/readthedocs/templates/docsitalia/overrides/builds/build_detail.html è caricato `knockout.js`
Verificare se serve anche a noi

_Originally posted by @francescozaia in https://github.com/italia/docs.italia.it/pull/324_

**Comment by yakky** [comment]
@carmelocatalfamo @francescozaia  quindi questa si può chiudere, giusto? Perché è usato upstream e quindi ce lo teniamo

**Comment by carmelocatalfamo** [comment]
@yakky si, si può chiudere.
Ho dato un'occhiata ai files che compongono `knockout.js`ed ho visto che viene usato per diverse cose, tra cui inviare una richiesta di build del documento.

**Comment by yakky** [comment]
🔝
