### ISSUE TITLE
404 su instantsearch.js

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#332]
Dopo l'upgrade risulta mancante il file `instantsearch.js`

Da verificare dove è dichiarato e se serve. 
<img width="1173" alt="slack-imgs com" src="https://user-images.githubusercontent.com/714711/67754918-88fdf200-fa37-11e9-92ff-5c85d9d15a86.png">

**Comment by carmelocatalfamo** [comment]
Closed #359
