### ISSUE TITLE
404 fontawesome

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#333]
Dopo l'upgrade risultato dei 404 su fontawesome

Verificare se sono da riportare dentro o se sono file obsoleti da togliere

<img width="1173" alt="slack-imgs com" src="https://user-images.githubusercontent.com/714711/67755063-c5315280-fa37-11e9-8d4d-032924cf61b7.png">

**Comment by carmelocatalfamo** [comment]
Closed #344
