### ISSUE TITLE
Testare e documentare l'upgrade da 2.3.13

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#334]
Testare e documentare l'upgrade sull'attuale staging

- [x] upgrade DB
- [x] drop indici ES
- [x] rigenerazione build documenti
- [x] fix URL dei documenti
- [x] link in pagina dei documenti di un progetto (`/comune-di-tre-civette-sul-como/anagrafe-di-tre-civette-sul-como/`)
- [x] link in pagina amministrazione (`/comune-di-tre-civette-sul-como/`)

**Comment by yakky** [comment]
ho creato un branch italia-dev come nuovo branch di sviluppo e sto facendo i test di upgrade
su un clone di staging le build falliscono ancora, ma conto di sistemarle presto (è sicuramente solo questione di configurazione): apro la pr sui deploy-scripts quando gira tutto e poi vado all'assalto di staging
l'unica rognetta è che bisogna usare per forza python 3.6 quindi l'upgrade richiede comunque un downtime perché bisogna piallare il virtualenv, ma confido che non sia un grosso problema anche su produzione (e comunque la consultazione pura possiamo lasciarla attiva)

**Comment by yakky** [comment]
Le segnalazioni relativamente all'url e alla mancanza nella pagina dei progetti erano dovute al documento di test in stato `private`. Una volta reso pubblico url e visibilità sono corretti.

@francescozaia confermi che è questo il comportamento giusto? Non ricordo onestamente

**Comment by francescozaia** [comment]
Corretto @yakky sì.
