### ISSUE TITLE
Verifica test automatizzati post upgrade

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#336]
Sistemare gli ultimi test ancora con problemi post-upgrade

- [x] search: https://github.com/italia/docs.italia.it/pull/354/files#diff-3feb65da93cbf0c035ce5046b25827b1R163 / da indagare
- [x] doc builder: https://github.com/italia/docs.italia.it/pull/354/files#diff-d40269401b82baa57f751f398da451faR44 / questo fallisce perchè in `readthedocs.docsitalia.utils.get_subprojects` facciamo una chiamata alle API per recuperare alcuni dati e il test non è "predisposto". Una possibile soluzione è marcarlo come expected fail e reimplementarlo in modo che accetti la chiamata API
- [x] 4 della ricerca `docsitalia` che vanno adattati alla nuova ricerca: https://github.com/italia/docs.italia.it/pull/354/files#diff-5d4295fb5d8c64f31085a17c79187ef9R19 / al contrario di prima nella suite di test adesso abbiamo elastic search che gira quindi possiamo togliere i mock e reimplementare i test anche usando il fixture già disponibili in `readthedocs.search` https://github.com/italia/docs.italia.it/blob/italia-dev/readthedocs/search/tests/conftest.py

**Comment by pauloxnet** [comment]
Attualmente i test lanciati con docker-compose sul branch [feature/issue-293-upgrade](https://github.com/italia/docs.italia.it/tree/feature/issue-293-upgrade) con questo comando:
```
PYTEST_ARGS="--create-db --no-migrations" docker-compose -f docker-compose-tox.yml run py36
```
produce questo risultato:
```
18 failed, 1437 passed, 10 skipped, 60 deselected, 2 xfailed, 7 xpassed, 2 warnings in 1246.81s (0:20:46)
```

**Comment by pauloxnet** [comment]
Questo è il primo tentativo di eseguire i test su travis: [Build #1005 - italia/docs.italia.it - Travis CI](https://travis-ci.org/italia/docs.italia.it/builds/604389455?utm_source=github_status&utm_medium=notification)

**Comment by yakky** [comment]
> Attualmente i test lanciati con docker-compose sul branch [feature/issue-293-upgrade](https://github.com/italia/docs.italia.it/tree/feature/issue-293-upgrade) con questo comando:
> 
> ```
> PYTEST_ARGS="--create-db --no-migrations" docker-compose -f docker-compose-tox.yml run py36
> ```
> 
> produce questo risultato:
> 
> ```
> 18 failed, 1437 passed, 10 skipped, 60 deselected, 2 xfailed, 7 xpassed, 2 warnings in 1246.81s (0:20:46)
> ```

Ho "scoperto" che su travis i test sono eseguiti con il flag ``--including-search``. L'ho aggiunto a tox in #354 e ora i risultati sono congruenti fra locale e travis

**Comment by yakky** [comment]
Per la ricerca bisogna capire lo scopo di https://github.com/italia/docs.italia.it/pull/98 ed eventualmente reimplementarlo nella nuova logica
