### ISSUE TITLE
Errore nel filtro bold-headers

### ISSUE THREAD

**Issue by danse** [italia/docs.italia.it#35]
@pablopers riporta un errore del filtro `bold-headers` applicato a questo documento https://github.com/pablopers/ISTATRapportoannuale2018. L'errore è:

    pandoc: Cannot decode byte '\x97': Data.Text.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream

**Comment by danse** [comment]
sembra collegato a questo https://github.com/jgm/pandoc/issues/3208, me lo studio

**Comment by danse** [comment]
@pablopers mi confermi che stai usando Windows?

**Comment by pablopers** [comment]
No, il comando è dato su Ubuntu Linux

Il lun 4 giu 2018, 15:10 Francesco Occhipinti <notifications@github.com> ha
scritto:

**Comment by danse** [comment]
incolleresti una copia del comando da console completo di output? Sulla mia Ubuntu eseguendo:

```
 ISTATRapportoannuale2018 (master)$ pandoc --filter ~/docsitalia-conversion-commands/pandoc-filters/filters/bold-headers.hs input.docx > /dev/null 
 ISTATRapportoannuale2018 (master)$ 
``` 
non ci sono errori, quindi si tratta di risalire ad un errore che entrambi sappiamo replicare

**Comment by danse** [comment]
non fare molto caso alla posizione del filtro nel mio sistema, visto che ero nel mezzo di un refactoring completo :sweat_smile:

**Comment by pablopers** [comment]
`(master)$ pandoc --filter bold-headers.hs input.docx > /dev/null
pandoc: Cannot decode byte '\x97': Data.Text.Encoding.Fusion.streamUtf8: Invalid UTF-8 stream
(master)$`

**Comment by danse** [comment]
bene grazie. Credo che questo errore possa essere collegato ad alcune impostazioni nella tua shell. Credo ci siano delle variabili che hanno effetto sul decoding che viene usato per leggere i files ... chercherò di riprodurre sul mio sistema modificando quelle variabili

**Comment by danse** [comment]
@pablopers per favore quando hai tempo potresti eseguire i seguenti comandi ed incollare il risultato?

    $ printenv | grep LC
    $ echo $LANG

**Comment by pablopers** [comment]
```
(master)$ printenv | grep LC
(master)$ echo $LANG
it_IT.UTF-8
(master)$
```

**Comment by danse** [comment]
altro comando per domani ... `echo | pandoc --filter bold-headers.hs` :)

**Comment by pablopers** [comment]
Sia nella directory dei filtri:
```
master:~/pandoc-docs2rst/pandoc-filters/filters$ echo | pandoc --filter bold-headers.hs
pandoc: Error running filter bold-headers.hs bold-headers.hs not found in path
master:~/pandoc-docs2rst/pandoc-filters/filters$
```

Sia in quella pandoc del progetto:
```
master:~/pandoc-docs2rst$ echo | pandoc --filter bold-headers.hs
pandoc: Error running filter bold-headers.hs bold-headers.hs not found in path
master:~/pandoc-docs2rst$
```

Ho anche cancellato la cartella pandoc-filters e lanciato il comando:
`git clone https://github.com/italia/pandoc-filters.git`
riprovato ma niente!
magari sbaglio io qualcosa...

**Comment by danse** [comment]
Strano, la documentazione per [l'opzione filtro](http://www.pandoc.org/MANUAL.html#general-options) dice che l'argomento può essere un percorso assoluto o relativo, che è il tuo caso quando esegui il comando da `pandoc-filters/filters`, quindi mi aspetterei che quel comando venga eseguito correttamente. Ho clonato una nuova versione di `pandoc-filters` nella cartella temporanea `/tmp` e poi da lì ho eseguito alcuni comandi, ecco il risultato:

```
$ cd /tmp/
tmp $ git clone https://github.com/italia/pandoc-filters/
tmp $ cd pandoc-filters/filters/
filters (master)$ pwd
/tmp/pandoc-filters/filters
filters (master)$ ls -l bold-headers.hs 
-rw-rw-r-- 1 francesco francesco 201 Jun  5 17:25 bold-headers.hs
filters (master)$ echo | pandoc --filter bold-headers.hs
 
filters (master)$ pandoc --version
pandoc 2.2
Compiled with pandoc-types 1.17.4.2, texmath 0.10.1.2, skylighting 0.7.0.2
filters (master)$ 
```

Quindi tutto per me funziona, con pandoc versione 2.2. Che versione hai tu?

Nota anche che l'errore adesso è diverso da quello che appariva prima, quindi mi chiedo in che cartella tu fossi quando eseguivi il comando `Cannot decode byte ...` scritto all'inizio di questa issue.

**Comment by danse** [comment]
credo che questo problema sia risolvibile meglio via chat, parliamone su developersitalia.slack.com ! :) La issue può restare aperta e la aggiornerò quando isoleremo meglio il problema

**Comment by danse** [comment]
la versione di pandoc fornita da ubuntu è 1.12 mentre noi vogliamo usare la più recente, o in alcuni casi il fork italiano. per adesso si può usare il nostro fork tramite `stack exec pandoc` in `pandoc-docs2rst` ma è molto scomodo. l'idea in futuro è che `docsitalia-comandi-conversione` esporti anche `pandoc` con la versione giusta

**Comment by danse** [comment]
a causa di questo problema di versione sto aggiungendo `pandoc` al set di comandi in `docs-italia-comandi-conversione` e credo che questo semplificherà parecchio la vita a tutti ... vedi a volte cosa può nascere a partire da un bug report? grazie @pablopers :raised_hands: !

**Comment by pablopers** [comment]
Grazie a te, felicissimo di aver contribuito!
