### ISSUE TITLE
🚨Certificato in scadenza

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#358]
## Dettagli
Il certificato di produzione (docs.italia.it) è in scadenza il prossimo weekend.

> Expires: Sunday, 10 November 2019 at 07:46:33 Central European Standard Time

Di norma basta un `cerbot renew`, se ci sono problemi durante la challenge con nginx vediamo assieme.

**Comment by yakky** [comment]
@francescozaia ho fatto un veloce check sulla procedura di rinnovo automatico e c'era un bachetto nella configurazione di nginx che lo impediva.
Ho sistemato, vediamo se rinnova da solo entro la giornata

**Comment by francescozaia** [comment]
> Expires: Saturday, 1 February 2020 at 20:06:10 Central European Standard Time

Grazie, chiudo
