### ISSUE TITLE
[verificato su staging] Cookie bar: allineamento testo e bottoni

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#376]
## Details
Per schermi piccoli il testo tocca i pulsanti.

<img width="408" alt="Screenshot 2019-11-17 at 10 17 26" src="https://user-images.githubusercontent.com/481084/69005547-ee9d1a00-0923-11ea-87f3-32497fdd9157.png">

Si dovrebbe aggiungere un margine verticale al paragrafo contenente i bottoni. Ad esempio qualcosa di tipo: `my-3 my-md-0`.

Approfittare di questa issue per sistemare i colori dei pulsanti stessi (usare `btn-primary` e `btn-outline-primary`)

**Comment by yakky** [comment]
Reopening for backport to staging

**Comment by yakky** [comment]
backported with 59af1f12e979e56b7de07c5a555111db7e2da466
