### ISSUE TITLE
[verificato su staging] Barra per comunicazioni in evidenza: spaziature

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#377]
## Details
Il testo contenuto nella barra per le comunicazioni in evidenza non ha margini su schermi medio-piccoli. Suggerirei qualcosa tipo `mx-4 text-center`.

<img width="601" alt="Screenshot 2019-11-17 at 10 23 38" src="https://user-images.githubusercontent.com/481084/69005573-5bb0af80-0924-11ea-8730-e2c513fb9a0e.png">

**Comment by yakky** [comment]
Reopening for backport to staging

**Comment by yakky** [comment]
backported with 8df43507bc9cbbe438a1d2e04d123efc992c4a72
