### ISSUE TITLE
[verificato su staging] File non trovato: instantsearch.js

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#378]
## Details
File non trovato:

`instantsearch.js:1 Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by yakky** [comment]
questo dovrebbe essere stato risolto da #359 , ma non ancora deployato su staging

**Comment by yakky** [comment]
Corretto da #359 e deployato su staging ieri / oggi
