### ISSUE TITLE
[verificato su staging] I loghi delle amministrazioni non vengono mostrati

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#379]
## Details
Le immagini hanno probabilmente un path non corretto. Si può verificare a questi link:

- https://docs-italia-staging.teamdigitale.it/cittametropolitananapoli/
- https://docs-italia-staging.teamdigitale.it/italia/

Mentre nella pagina dedicata alla lista delle [Amministrazioni](https://docs-italia-staging.teamdigitale.it/amministrazioni/) si vedono correttamente.

**Comment by yakky** [comment]
@SimoneNephila @carmelocatalfamo a occhio manca un `{{ MEDIA_URL }}` nel template o qualcosa di simile

**Comment by carmelocatalfamo** [comment]
Appunto qui la soluzione:

@SimoneNephila se sei libero e vuoi occupartene tu fai pure, altrimenti ci penso io appena finisco di lavorare sull'altro branch :)

Ho verificato il problema e quei loghi vengono pescati direttamente da github.
Basta sostituire `publisher.metadata.publisher.logo` con `publisher.metadata.publisher.logo_url` alla righe `16` e `17`
