### ISSUE TITLE
[verificato su staging] Rimuovere un paragrafo contenente link invalido

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#380]
## Details
Visto che abbiamo rimosso la board Trello, nella [pagina "Che cos'è Docs Italia"](https://docs-italia-staging.teamdigitale.it/che-cos-e-docs-italia/) rimuovere il paragrafo _"Per saperne di più, segui la nostra board su Trello."_

**Comment by yakky** [comment]
Reopening for backport to staging

**Comment by yakky** [comment]
backported with d23cc05839eb3583bc770a910d5de41bba901dba
