### ISSUE TITLE
[verificato su staging] Link obsoleti

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#381]
## Details
Nella home page il testo sotto il titolo “Che cos'è Docs Italia” contiene un link al Codice dell’Amministrazione Digitale punta ad una vecchia versione del documento.
https://docs.italia.it/italia/piano-triennale-ict/codice-amministrazione-digitale-docs/it/v2017-12-13/
è da sostituire con
https://docs.italia.it/italia/piano-triennale-ict/codice-amministrazione-digitale-docs

Analogo problema nella pagina “Che cos'è Docs Italia”
https://docs-italia-staging.teamdigitale.it/che-cos-e-docs-italia/

**Comment by yakky** [comment]
Reopening for backport

**Comment by yakky** [comment]
backported with 7de770785a7b340bd80a970e4d306aa4be9ba62e
