### ISSUE TITLE
[verificato su staging] Stile "card": divisori e icone

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#382]
## Details
È andato perso lo stile delle card che aggiungeva il bordo a destra e la linea in basso ai singoli documenti nelle liste. Dovrebbe essere sufficiente aggiungere la classe `document-card` all'elemento con classe `card-wrapper`.

Il risultato dovrebbe essere come su docs.italia.it:
<img width="293" alt="Screenshot 2019-11-17 at 10 31 41" src="https://user-images.githubusercontent.com/481084/69005650-8b13ec00-0925-11ea-9593-93f1c064a945.png">

Inoltre, le icone dovrebbero rimanere sempre allineate in alto, o comunque non si dovrebbe creare questo effetto poco piacevole nel caso di titoli su più righe:

<img width="1121" alt="2" src="https://user-images.githubusercontent.com/481084/69005682-d9c18600-0925-11ea-96a1-2bdeaf12aead.png">

Se possibile, vedere anche di limitare il numero di righe che si vengono a creare, magari usando una spaziatura minore.

**Comment by yakky** [comment]
Riapro per fare il backport della PR colllegata

**Comment by yakky** [comment]
backported with c9040ea32aa53e412b36a7c20e705d168447a12f
