### ISSUE TITLE
[verificato su staging] Apostrofo nel nome del progetto

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#385]
## Details
Problema di encoding nel nome del progetto, vedere ad esempio:
https://docs-italia-staging.teamdigitale.it/italia/piano-triennale-ict/cloud-docs/it/master/index.html

([su docs.italia.it](https://docs.italia.it/italia/piano-triennale-ict/cloud-docs/it/stabile/) sembra ok)

<img width="564" alt="5" src="https://user-images.githubusercontent.com/481084/69005721-5c4a4580-0926-11ea-8b4f-16428d59a829.png">

**Comment by yakky** [comment]
questo potrebbe riguardare il tema (quella pagina è nella doc generata) :thinking: ma non capisco perché

**Comment by francescozaia** [comment]
Secondo me il tema non è cambiato, per cui non saprei... forse @pdavide può aiutarci per sapere da dove arriva quel dato.

**Comment by yakky** [comment]
> Secondo me il tema non è cambiato, per cui non saprei... forse @pdavide può aiutarci per sapere da dove arriva quel dato.

@francescozaia si "non capisco perché" si riferiva (in modo criptico) al fatto che la versione del tema dovrebbe essere la stessa
Potrebbe anche essere che il `conf.py` generato ha la codifica sbagliata

**Comment by yakky** [comment]
@francescozaia risolto con una rigenerazione della build: alcuni rebuild non sono partiti
magari stasera rilancio una rigenerazione completa delle build per essere sicuri che sia a posto

master dopo rebuild: https://docs-italia-staging.teamdigitale.it/italia/piano-triennale-ict/cloud-docs/it/master/index.html
bozza non ribuildato: https://docs-italia-staging.teamdigitale.it/docs/cloud-docs/it/bozza/

**Comment by yakky** [comment]
Ho lanciato un rebuild completo cosi puoi verificare
nel frattempo chiudo questa issue
Ovviamente se il problema è comunque presente riapri pure
