### ISSUE TITLE
[verificato su staging] Presenza di documento non valido nei risultati ricerca

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#386]
## Details
Con riferimento a #248 , cercando `xyz`: https://docs-italia-staging.teamdigitale.it/search/?q=xyz&type=file&version=bozza, l'unico documento trovato non risponde correttamente, capire perché viene mostrato se invalido.

**Comment by yakky** [comment]
questo potrebbe essere un problema di build, lo prendo io

**Comment by yakky** [comment]
@francescozaia questo è in qualche modo collegato a #392 
Nel db esistono ancora i docs usati per l'indicizzazione di questo progetto ma i file html non esistono più e il progetto non builda (mancano i branch)
dal momento che i dati nel db ci sono viene indicizzato ma poi mancano i file e le versioni non possono essere cancellate a causa di #392 
In altre parole l'indicizzazione funziona ma sta indicizzando dati vecchi che non possiamo aggiornare, abbiamo due strade:
1) lasciamo aperta la issue e la chiudiamo insieme a #392 dopo aver cancellato le versioni e verificato la reindicizzazione
2) cancello il progetto e reindicizzo, se non compare più chiudo la issue
