### ISSUE TITLE
[verificato su staging] L'inserimento dei tag/etichette non funziona

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#387]
## Details
Con riferimento a #257 , nella pagina di amministrazione di un documento non si possono inserire tag (verificato in varie condizioni), dice sempre "No result found" (che sarebbe bene tradurre).

![3](https://user-images.githubusercontent.com/481084/69005783-22c60a00-0927-11ea-8d95-f6bc76c0777e.gif)

Inoltre, nella stessa pagina, c'è un errore in console riguardo il file `https://docs-italia-staging.teamdigitale.it/media/static/admin/css/autocomplete.css` non trovato.

**Comment by yakky** [comment]
Probabilmente non ho caricato il vocabolario dei tag al deployment :man_facepalming:

**Comment by francescozaia** [comment]
Fosse solo quello, sarebbe ottimo 😄

**Comment by yakky** [comment]
@francescozaia confermo, ho caricato il vocabolario e ora riesco ad associarli

**Comment by francescozaia** [comment]
Confermo, ottimo!
Chiederei solo un passaggio a @carmelocatalfamo per sistemare un po' il layout che non tiene benissimo aggiungendo più tag.

<img width="486" alt="Screenshot 2019-11-18 at 10 19 27" src="https://user-images.githubusercontent.com/481084/69039932-35a31200-09ed-11ea-9c0d-72b4d9ebf2a2.png">

Si potrebbe:
- Sostituire alla "x" che è poco chiara un "Elimina tutti i tag" e/o posizionarlo in modo assoluto per evitare che collida con i tag man mano che vengono aggiunti.
- Fare il div `select2 select2-container` a tutta larghezza, perché non ha senso così stretto.
- Togliere `border-radius` a `.select2-container--default .select2-selection--multiple` ed usare lo stesso colore di bordo degli altri campi nella pagina.

**Comment by yakky** [comment]
@francescozaia posso creare una nuova issue per questa segnalazione? Renderebbe più semplice la gestione

**Comment by francescozaia** [comment]
Ovvio, sentiti libero di copiare/tagliare incollare ciò che vuoi.

**Comment by yakky** [comment]
Aperta come #399 , cosi questa la chiudiamo con quella che aggiunge il comando per importare i tag
