### ISSUE TITLE
[verificato su staging] Sync repository pending

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#388]
## Details
Non sono sicurissimo di questa issue perché potrebbe essere un problema della mia rete, ma nella schermata di importazione dei documenti (https://docs-italia-staging.teamdigitale.it/docsitalia/dashboard/import/), quando clicco l'iconcina in alto per aggiornare i repository, rimane in attesa.

**Comment by yakky** [comment]
Confermo
@Amanit @pauloxnet la chiamata e il task partono correttamente, forse non viene aggionato lo stato sul db e quindi il polling va avanti all'infinito

**Comment by pauloxnet** [comment]
@yakky @francescozaia in remoto in effetti il sync rimane pending ma per completezza dei test ho provato in locale e dopo alcuni secondi il polling si interrompe senza errori (ma con alcuni warning nel mezzo).

Se il problema è nel codice, questo verrà fixato dopo il deploy della PR di ricerca su staging, se invece il problema risiede nelle instanze celery che si occupano dell'operazione sarebbe da verificare.

**Comment by francescozaia** [comment]
Non vorrei aggiungere altre cose a staging prima di portare tutto in
produzione.
Però ci confrontiamo meglio domattina!
