### ISSUE TITLE
[verificato su staging] È sparito il menu "Admin">"Versions"

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#392]
## Details
Non so se è una regressione o cosa, ma non è più visibile il menu "Versions" nell'area amministrativa, che è fondamentale per poter scegliere quali versioni usare o rendere pubbliche.
<img width="793" alt="Screenshot 2019-11-17 at 15 38 32" src="https://user-images.githubusercontent.com/481084/69050640-c6d0b380-0a02-11ea-9905-5ddcda7d9930.png">

**Comment by yakky** [comment]
@Amanit @pauloxnet questo sembra sia stato tolto da upstream (anche a livello BE), da verificare da cosa sia stato sostituito

**Comment by pauloxnet** [comment]
@yakky @francescozaia se parlate del menu Admin > Builds > Versions io nel branch di ricerca in  locale lo vedo

**Comment by francescozaia** [comment]
Parlo di quel Versions che c'è online ma non su staging, ho aggiunto uno screenshot alla issue.
Questo è invece produzione:
<img width="660" alt="Screenshot 2019-11-18 at 12 55 09" src="https://user-images.githubusercontent.com/481084/69050599-b4567a00-0a02-11ea-90e0-84db35848578.png">

**Comment by yakky** [comment]
@pauloxnet @carmelocatalfamo dovrebbe essere solo un problema di template, è stato spostato nella toolbar principale :sweat_smile: 

![screenshot da repo su rtd.org](https://user-images.githubusercontent.com/714711/69052559-9e978380-0a07-11ea-8626-66481935547c.png)

**Comment by francescozaia** [comment]
Ok ottimo allora basta ri-aggiungerlo lì. Infatti è parecchio importante! 😅

**Comment by Amanit** [comment]
Questa pagina di Versions era spostata fuori da Admin.
Quindi io posso ri-aggiungere in menu di Admin ma appena click'a su link usciamo fuori.
![Screenshot from 2019-11-19 10-15-31](https://user-images.githubusercontent.com/4007078/69133331-05737600-0ab6-11ea-82bb-63d3d5af149d.png)

Forse meglio fare come in Upstream e aggiungere questo link in toolbar principale?

**Comment by Amanit** [comment]
Cosi
![Screenshot from 2019-11-19 10-24-49](https://user-images.githubusercontent.com/4007078/69133907-f640f800-0ab6-11ea-872f-81aa6a3bfd28.png)

**Comment by yakky** [comment]
@Amanit allineerei la nostra barra a quella di RTD
e lo farei anche per la sidebar della sezione admin togliendo quello che non ci interessa
vedi sotto
![Screenshot_20191119_143935](https://user-images.githubusercontent.com/714711/69151301-ad029f80-0ada-11ea-9129-abb3a61847a1.png)

@francescozaia quelli in rosso potrebbero in realtà essere interessanti anche se per il momento li nasconderei comunque
