### ISSUE TITLE
Migrare codice custom ricerca in docsitalia

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#400]
## Details

Attualmente in `readthedocs.search` ci sono diversi inserimenti di codice custom (principalmente in `views.py`, `documents.py` e `faceted_search.py`

Questo ci può creare parecchi problemi in futuri aggiornamenti di versione e bisogna quindi trovare il modo di rifattorizzare questi moduli in modo da minimizzare l'impatto

**Comment by yakky** [comment]
@pauloxnet appuntiamo qui idee su come affrontare la questione

**Comment by pauloxnet** [comment]
Il codice presente in quei file deriva dal porting delle funzioni precedentemente inserite nel branch [italia-2.3.13](https://github.com/italia/docs.italia.it/tree/italia-2.3.13) e la migrazione al di fuori di quei file potrebbe richiedere parecchio tempo e modifiche anche nei test.

Potremmo apportare variazioni progressive al codice per minimizzare i conflitti con il codice master di RTD, secondo  gli step posso essere questi 3:

1. Allineare il codice a quello del branch master di RTD (usando un compare) ripristinando anche eventuali errori di formattazione corretti da noi ma che aumentano solo le differenze nel compare senza apportare nuove funzionalità, in modo da minimizzare il numero di cancellazioni e modifiche tra i due branch se non relative a nostre funzioni (questo è in parte già fatto ma sarebbero da controllare tutti i file)

2. Modificare il codice da noi aggiunto nei file (forse diminuendone la pulizia) per minimizzare il numero di modifiche e cancellazioni al codice originario (es: aggiungere valori nelle variabili in righe successive a quelle originali). Portando il nostro codice ad essere per la maggior parte righe di codice aggiunto rispetto al master di RTD ci permetterebbe di riportare molto più facilmente i commit nel nostro fork.

3. Spostare il codice di ricerca ed eventualmente altro in viste personalizzate cercando di ereditare quelle di RTD, usare un `ROOT_URLCONF` separato nel nostro file di settings per indirizzare usare le nostre viste personalizzate, ed infine aggiornare tutti i test.

**Comment by pauloxnet** [comment]
In base a quanto detto in riunione con @francescozaia rimuoverei tutte le modifiche al codice che riguardano la ricerca dei Progetti dal momento che non utilizziamo questo tipo di ricerca.
