### ISSUE TITLE
Rendere ricercabile la versione che si sceglie come default all'interno del documento

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#403]
## Details

Per ovviare a diversi problemi  (#242 sopratutto) è necessario non ricercare di default su `latest` (ovvero `bozza`) come fa RTD, ma una versione che l'utente può selezionare

A tale scopo possiamo usare `Project.default_version`

Implementazione
- modificare `PageDocument.version` usando un `prepare` per forzare una stringa arbitraria
- modificare `PageSearchBase` per usare questa stringa di ricerca come versione su cui filtrare

Problemi
- è necessario modificare il comando di rebuild per "conoscere" il concetto di `default` per poter fare la ricerca 
- nel template non può essere usata la versione che arriva da ES per costruire l'url perché non è una versione valida. Si può aggiungere un altro attributo da usare

**Comment by yakky** [comment]
fare uno spike esplorativo sul branch `feature/363-ricerca`

**Comment by pauloxnet** [comment]
> fare uno spike esplorativo sul branch `feature/363-ricerca`

Il branch `feature/363-ricerca`è stato mergiato su `italia-dev`
