### ISSUE TITLE
Aggiungere i filtri per versione "default", "bozza", "stabile" nella SERP

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#404]
Alla luce di quanto deciso di implementare in #403, abbiamo deciso di lasciare all'utente la possibilità di poter filtrare, dal menu sulla sinistra nella SERP, per le seguenti versioni:
- "default"
- "bozza"
- "stabile"

Andremo in seguito a definire eventuali help contestuali per chiarire meglio agli utenti la differenza tra le tre possibilità di scelta.

**Comment by pauloxnet** [comment]
Direi di in questo task di aggiungere il filtro in colonna per versione con i valori "bozza" e "stabile" e aggiungere il valore "default" nel task che aggiunge effettivamente questo valore ovvero il #403

**Comment by pdavide** [comment]
Piccolo problema UX: nella SERP, quando si seleziona il filtro bozza, dopo il refresh cambia l'ordine dei filtri bozza/stabile.

**Comment by yakky** [comment]
@filippo-20tab ho riaperto a seguito della segnalazione di davide, vediamo poi come organizzarci

**Comment by Amanit** [comment]
@pdavide ho aggiunto ordering del Version filter

**Comment by yakky** [comment]
@pdavide @francescozaia fix sull'ordine delle versioni deployato
