### ISSUE TITLE
All'interno di un documento non è possibile cambiare la versione selezionata

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#408]
## Details
@yakky segnalo qui per tenerne traccia, anche se forse è solo un problema mio:
sto vedendo il documento sulle LG di design qui: http://new.docs-italia-staging.teamdigitale.it/italia/designers-italia/design-linee-guida-docs/it/stabile/index.html (host sulla macchina di dev `docs-italia-prod-tmp-vm-dev-01 - 52.142.230.205`).

Non mi è possibile cambiare versione del documento, selezionando dal menu a tendina.

**Comment by yakky** [comment]
@francescozaia questo riguarda staging, giusto? su produzione (ip .206 finale) non riscontro il problema

**Comment by yakky** [comment]
confermato, si verifica anche su https://docs-italia-staging.teamdigitale.it/italia/anpr/anpr/it/test-docs-italia/index.html

Riguarda sicuramente questa parte qui https://github.com/italia/docs-italia-deploy-scripts/blob/feature/issue-293-upgrade/roles/app/templates/nginx/sites-available/readthedocs-main.conf#L87
