### ISSUE TITLE
[verificato su staging] Pagina backoffice, allineamento compilazioni tabella visualizzazione su smartphone

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#429]
## Details
Su schermi piccoli, il layout delle pagine private dei documenti è molto migliorabile:

- I tasti del menù si sovrappongono in verticale (testato con smartphone Pixel3A, il problema non sembra essere replicabile sul desktop riducendo la finestra nel browser)
- manca un margine a sinistra del titolo
- nell'account personale manca un margine a sinistra dell’avatar e del tasto “Profilo”
- la tabella delle compilazioni è da sistemare:

<img width="348" alt="Screenshot 2019-12-02 at 14 50 39" src="https://user-images.githubusercontent.com/481084/69964706-1fc83d80-1513-11ea-88aa-6a307dc6bc8d.png">

Correlata a #430

**Comment by yakky** [comment]
a 360px lo vedo così 
![image](https://user-images.githubusercontent.com/714711/71322136-6b438b00-24c4-11ea-9c8c-21b33cabf580.png)

**Comment by francescozaia** [comment]
Anch'io vedo la UI molto migliorata sia su desktop ridimensionato che su mobile (a sinistra staging, a destra produzione).
![compare](https://user-images.githubusercontent.com/481084/71347196-14908c80-256a-11ea-8399-f45a0176eb91.jpg)

**Comment by yakky** [comment]
@francescozaia quindi si può chiudere giusto?

**Comment by francescozaia** [comment]
Aspettavo un ultimo feedback da @luciopileggi

**Comment by yakky** [comment]
:+1:

**Comment by luciopileggi** [comment]
Testato su brwoser e su smartphone. Anche per me questa issue è risolta.

**Comment by yakky** [comment]
@luciopileggi @francescozaia :bowing_man: chiudo
