### ISSUE TITLE
[verificato su staging] Pagina Versioni: tabella versioni e descrizione “sforano” a destra nella visualizzazione su smartphone

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#430]
## Details
Su schermi piccoli, il layout della pagina privata delle versioni dei documenti si rompe perché la tabella fa sì che il layout scorra in orizzontale quando non dovrebbe:
<img width="328" alt="Screenshot 2019-12-02 at 15 02 39" src="https://user-images.githubusercontent.com/481084/69965584-d8db4780-1514-11ea-9902-530a687aca6a.png">
e
<img width="334" alt="Screenshot 2019-12-02 at 16 29 43" src="https://user-images.githubusercontent.com/481084/69972028-2493ee00-1521-11ea-87e2-0b7602b10cf8.png">

Correlata a #429

**Comment by yakky** [comment]
@francescozaia lo vedo così 
![image](https://user-images.githubusercontent.com/714711/71322145-a0e87400-24c4-11ea-9eed-49e3a7769f37.png)

**Comment by francescozaia** [comment]
Anch'io lo vedo bene (anche i bottoni correttamente spaziati), @luciopileggi tu?

**Comment by luciopileggi** [comment]
E' risolto anche per me.
