### ISSUE TITLE
Broken link to source in ANPR docs

### ISSUE THREAD

**Issue by bfabio** [italia/docs.italia.it#436]
In the ANPR documentation at https://docs.italia.it/italia/anpr/anpr/it/stabile/index.html and its children sections, the Source button in the top right hand side links to https://github.com/italia/anpr/blob/77fc9db91f45af433664aba3aef290a82a65e1b3/src/index.rst, which is a 404.

**Comment by bfabio** [comment]
It's fixed now.

**Comment by yakky** [comment]
Thanks for reporting. apparently the build was stuck on an old (and not existing) commit
I forced a doc rebuild to fetch the right one
