### ISSUE TITLE
[verificato su staging] z-index autocomplete

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#440]
## Details

La funzionalità di autocomplete su staging ha un problema di z-index

![image](https://user-images.githubusercontent.com/714711/70788799-f8cefe80-1d91-11ea-873b-698164c45eba.png)

**Comment by carmelocatalfamo** [comment]
Ho verificato in locale e su [old.dev.docs.italia.it](https://old.dev.docs.italia.it/) ma sembra tutto funzionante. Ho provato con Chrome e Firefox.

@yakky potrebbe essere un problema di cache, puoi controllare nuovamente per favore? :)

![image](https://user-images.githubusercontent.com/11672358/70791626-b9a3ac00-1d97-11ea-8d9b-9bc9d493ac6e.png)

**Comment by yakky** [comment]
@carmelocatalfamo hai ragione
ovviamente è la cache :D
