### ISSUE TITLE
[verificato su staging] comportamento anomalo selettore paginazione

### ISSUE THREAD

**Issue by pauloxnet** [italia/docs.italia.it#444]
Nella pagina di SERP  come ad esempio la seguente:
https://old.dev.docs.italia.it/search/?q=documento&type=file
selezionando il page_size 48 e poi andando avanti o dietro scompaiono i valori dalla select e vengono mostrati solo 12 risultati per pagina come in immagine in allegato
![Screenshot_2019-12-13 Docs Italia](https://user-images.githubusercontent.com/521097/70798067-48b7c080-1da6-11ea-87bd-3aee3392c1b2.png)

**Comment by Amanit** [comment]
@pauloxnet non riesco a riprodurre adesso. Ancora esiste questa errore?

**Comment by yakky** [comment]
@pauloxnet anche io non riesco a riprodurlo. lo inserisco nella board di testing

**Comment by pauloxnet** [comment]
Ho catturato los creenshot allegato su Firefox 71 in Ubuntu 19.10

Provando adesso di nuovo non riesco nemmeno io a riprodurre più il problema.

**Comment by yakky** [comment]
lo chiudo comunque, tanto rimane nella board di test
