### ISSUE TITLE
Missing content in ANPR docs

### ISSUE THREAD

**Issue by bfabio** [italia/docs.italia.it#446]
I think there's some missing content at https://docs.italia.it/italia/anpr/anpr/it/stabile/faq/index.html and https://docs.italia.it/italia/anpr/anpr/it/stabile/comuni/index.html, namely the index of content and the link to `cosa-cambia-comune-migrato.md`.

**Comment by yakky** [comment]
@bfabio this is most likely a problem with the document itself, you could probably open the issue on the related repo https://github.com/italia/anpr
Bear in mind the the version on docs italia is the tagged one https://github.com/italia/anpr/releases not master

**Comment by bfabio** [comment]
Thanks @yakky! I was actually unsure where to open it because the bug tracker of https://github.com/italia/anpr looked like was reserved to support issues.
