### ISSUE TITLE
Style of the bullet points can lead to confusion

### ISSUE THREAD

**Issue by bfabio** [italia/docs.italia.it#447]
The current style of bullet points is an arrow pointing right which looks exactly like an expanding arrow

![Screenshot](https://user-images.githubusercontent.com/788293/70860088-488e0100-1f1d-11ea-8158-b4a19efb8e59.png)

I have to resist the urge of clicking it every single time to reveal more content.

**Comment by yakky** [comment]
@bfabio if it's in the rendered docs, please open the issue on https://github.com/italia/docs-italia-theme
Otherwise I think it's a style that comes from https://github.com/italia/bootstrap-italia

pinging @francescozaia on this

**Comment by bfabio** [comment]
> @bfabio if it's in the rendered docs, please open the issue on https://github.com/italia/docs-italia-theme

Done, thanks for the pointer.

**Comment by francescozaia** [comment]
Closing, as it's now on https://github.com/italia/docs-italia-theme/issues/187
