### ISSUE TITLE
Tuning ricerca full-text

### ISSUE THREAD

**Issue by pauloxnet** [italia/docs.italia.it#450]
Verifica delle segnalazioni siu test di ricerca full-text ed affinamento delle logiche di indicizzazione e ricerca full-test su Elastic search

**Comment by pauloxnet** [comment]
Segnalazioni riportate sul canale slack da @pdavide :

# Caso 1
Risulta impossibile trovare mediante ricerca il documento (pubblico) https://docs.italia.it/AgID/documenti-in-consultazione/lg-spid-firma-docs/it/stabile/index.html
ho notato che anche usando una chiave contenuta nel titolo del documento (“sottoscrizione”) il documento non appare nella serp. Guardando la querystring ho notato che appare un filtro predefinito type=file che, se rimossa, permette di trovare il documento (https://docs.italia.it/search/?q=sottoscrizione).
In generale mi sembra di capire che type=file attivi una modalità fulltext sui documenti che, in base al tipo di ricerca, può dare risultati poco utili (stesso documento presente molte volte nella serp). Si potrebbe pensare di attivare la fulltext solo con un flag apposito? Oppure provare ad includere il titolo (con un peso maggiore) anche nelle ricerche fulltext?

# Caso 2
rispetto al documento https://docs.italia.it/AgID/documenti-in-consultazione/lg-spid-firma-docs/it/stabile/index.html se uso una stringa lunga contenuta nel testo come chiave di ricerca non trovo il documento nella serp, se aggiungo le virgolette ottengo una serp vuota:

- https://docs.italia.it/search/?q=Le+richieste+e+risposte+di+autenticazione+SAML+impiegano+session+ID&type=file

- https://docs.italia.it/search/?q=%22Le+richieste+e+risposte+di+autenticazione+SAML+impiegano+session+ID%22&type=file&version=bozza

**Comment by pauloxnet** [comment]
Ho effettuato i testi sull'attuale istanza di Staging e la ricerca sembra stia funzionando correttamente ma l'ordinamento predefinito nella SERP per risultati "Più popolari" potrebbe confondere l'utente.

# Steps

Ecco di segui i test che ho portato avanti :

1. Ho individuato un documento a caso che voglia provare a cercare e che mi aspetto https://old.dev.docs.italia.it/italia/funzione-pubblica/foia-circolare2-docs/it/bozza/index.html

2. Ho usato `Accesso civico generalizzato`, cioè la prima parte del nome del documento, nella ricerca veloce della modale ed il documento che mi viene proposto per primo è esattamente quello previsto
![Screenshot_2019-12-19 Docs Italia(1)](https://user-images.githubusercontent.com/521097/71192130-fedc4800-2287-11ea-9082-01c54324da07.png)

3. Se proseguo la ricerca nella pagina SERP mantenendo la paginazione predefinita (12 risultati per pagina) e l'ordinamento predefinito (con priorità per i più popolari) siamo costretti a scorrere fino alla pagina 14 di 25 per visualizzare il nostro risultato atteso a metà dei risultati della pagina
![Screenshot_2019-12-19 Docs Italia(2)](https://user-images.githubusercontent.com/521097/71192211-1d424380-2288-11ea-86e7-4be5276ebf03.png)

4. Se invece nella pagina di SERP utilizziamo l'ordinamento "rilevanza" allora troveremo il nostro risultato atteso nella prima posizione della prima pagina
![Screenshot_2019-12-19 Docs Italia](https://user-images.githubusercontent.com/521097/71192249-32b76d80-2288-11ea-8b89-afef8aaf0dd8.png)

# Conclusione

Vista la confusione da parte dell'utente che ha eseguito i test nel nostro trovare il risultato atteso direi che la ricerca funziona in modo atteso ma l'ordinamento predefinito potrebbe essere cambiato da "Più popolari" in "Rilevanza".

**Comment by francescozaia** [comment]
Grazie dell'investigazione, sono d'accordo anch'io che l'ordinamento predefinito debba essere "rilevanza".

**Comment by filippo-20tab** [comment]
Grazie @pauloxnet dell'esaustiva indagine. Concordo col cambiamento dell'ordinamento di default come soluzione rapida. Come sai, non mi trovo d'accordo con l'idea di fondo dell'ordinamento "Più popolari" che, così com'è stato pensato, risulta più un filtro che un criterio di ordinamento e confonde l'utente.

**Comment by pdavide** [comment]
Nell'istanza `old.dev` (non sono sicuro che sia quella giusta da usare), se in [questa ricerca](https://old.dev.docs.italia.it/search/?q=Specifiche%20Attuative%20del%20Nodo%20dei%20Pagamenti-SPC%20versione%202.2.6&type=file) provo a cambiare il criterio in "rilevanza" si genera un refresh della pagina che torna di nuovo su "più popolari".

**Comment by yakky** [comment]
> Nell'istanza `old.dev` (non sono sicuro che sia quella giusta da usare), se in [questa ricerca](https://old.dev.docs.italia.it/search/?q=Specifiche%20Attuative%20del%20Nodo%20dei%20Pagamenti-SPC%20versione%202.2.6&type=file) provo a cambiare il criterio in "rilevanza" si genera un refresh della pagina che torna di nuovo su "più popolari".

@pdavide l'istanza è giusta , confermo il problema.
Stranamente gli altri ordinamenti funzionano correttamente

**Comment by carmelocatalfamo** [comment]
@yakky  @pdavide 
Avevo corretto questo funzionamento in [questa pull request](https://github.com/italia/docs.italia.it/pull/448/files#diff-8b298c6c036979addcb7dc2859374bbcR8).

**Comment by yakky** [comment]
@carmelocatalfamo perfetto, allora faccio il deploy

**Comment by yakky** [comment]
@pauloxnet @francescozaia @pdavide il fix del reload della pagina è caricato
Bisogna solo modificare il default a questo punto

**Comment by pdavide** [comment]
Grazie ragazzi, ottimo lavoro!
Fatemi sapere quando il fix sarà deployato in prod così lo comunico all’owner del documento.

**Comment by pauloxnet** [comment]
@francescozaia @pdavide abbiamo apportato la modifica ed a breve sarà deployata su `old.dev` quindi vi chiedere di testare di nuovo la ricerca.
