### ISSUE TITLE
[verificato su staging - nuovo] Errori in console all'interno dei documenti

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#454]
## Details
Con Chrome, entrando in un documento, ad esempio https://old.dev.docs.italia.it/italia/spid/spid-regole-tecniche/it/stabile/index.html, si possono notare molti errori in console, tra cui:

- `The page ... was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://new.docs-italia-staging.teamdigitale.it/docsitalia/api/document/spid-regole-tecniche/active_versions/?_=1577091902198'. This request has been blocked; the content must be served over HTTPS.`  e molte altre simili
- `Uncaught ReferenceError: LOCAL is not defined at Object.error (theme.js:1)`

A occhio, potrebbero essere tutte causate da una semplice configurazione del dominio usato dal tema per usare le API (tale setting potrebbe essere anche nel repo `docs-italia-deploy-scripts` o in qualche configurazione server).

**Comment by yakky** [comment]
@francescozaia potresti provare a rifare una build del documento?

**Comment by francescozaia** [comment]
Wow magia. Va tutto ok. Che è cambiato, c'è qualche procedura da gestire?

**Comment by yakky** [comment]
@francescozaia in realtà no. era un documento non ricompilato dopo il passaggio del dominio del nuovo staging da quello temporaneo a quello definitivo.
In generale tutte le volte che cambia il dominio sullo stesso server devono essere ricompilati tutti i documenti
È una cosa che si può documentare (dove?) ma è una situazione più unica che rara

**Comment by francescozaia** [comment]
Confermo che è importante ribuildare tutto al cambio di ambiente, molti documenti hanno comportamenti strani finché non vengono ricompilati.
