### ISSUE TITLE
[verificato su staging - nuovo] Il numero di documenti trovati non è corretto

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#456]
## Details
Come mostrato nello screenshot della SERP per "documento" (che ha centinaia di match), il numero in alto nella pagina dovrebbe mostrare il numero totale dei documenti trovati, non quello dei documenti visualizzati per pagina.

Se vogliamo evidenziare la presenza della paginazione, si potrebbe mostrare "12 di xxx risultati".

<img width="1269" alt="Screenshot 2019-12-23 at 10 58 07" src="https://user-images.githubusercontent.com/481084/71351310-a781f480-2573-11ea-883a-c7110ad91030.png">

**Comment by yakky** [comment]
assegno anche filippo e carmelo, il primo che si libera la prende  :)

**Comment by yakky** [comment]
(così a occhio: nel template prendiamo il numero di hit dall'oggetto pagina, non quello dell'oggetto ricerca)
