### ISSUE TITLE
Ricerca case insensitive sui tag

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#482]
## Details

La ricerca per tag dovrebbe essere case insensitive

* modificare indici
* dal momento che il problema riuguarda solo il click sul tag nelle pagine di ricerca, può essere più semplice inserire direttamente il valore minuscolo (che è quello effettivamente indicizzato)

**Comment by Amanit** [comment]
@pdavide come si puo riprodurre questo bug senza scrivere url a mano?

**Comment by pdavide** [comment]
@Amanit la prova che farei è buildare un documento che contiene in document_settings un tag allowed in uppercase e vedere come si comporta la ricerca al click sul nome del tag dalla modale info del documento.
