### ISSUE TITLE
Eliminare tag non ammessi dai documenti esistenti

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#483]
## Details

I documenti esistenti vanno ripuliti dai tag non ammessi già associati

Conviene creare un command per avere più controllo sull'esecuzione della procedura

**Comment by yakky** [comment]
@pdavide @francescozaia vi torna?

**Comment by francescozaia** [comment]
Sì, confermo che ogni tag non ammesso (non presente nella lista allegata a https://github.com/italia/docs.italia.it/issues/257) non dovrebbe comparire in alcuna parte del sito, nemmeno nei vecchi documenti.
