### ISSUE TITLE
Non si può deselezionare tag nelle view di ricerca per tag

### ISSUE THREAD

**Issue by yakky** [italia/docs.italia.it#484]
## Details
nelle serp di ricerca con tag (es. https://old.dev.docs.italia.it/ricerca/tag/design/) non è possibile deselezionare il tag dalla col sx (neanche dopo aver selezionato un altro tag)

**Comment by francescozaia** [comment]
@pdavide con che browser avviene? A me sembra funzionare.

EDIT: @yakky vedo che forse hai risolto poco fa

**Comment by yakky** [comment]
@francescozaia si, ho fatto un hotfix al volo per capire se era la soluzione giusta
La #485 è la risoluzione comprensiva di test
