### ISSUE TITLE
Nuova pagina "Amministrazioni" che listi tutti i publisher

### ISSUE THREAD

**Issue by francescozaia** [italia/docs.italia.it#92]
Creazione di una pagina "Amministrazioni" (che in futuro diventerà [questa](https://invis.io/AQMX2Y2GTH2#/308140023_it_Docs_sezione_amministrazioni)), che listi tutte le amministrazioni con documentazioni attive.

**Comment by xrmx** [comment]
Non abbiamo la tipologia dell'ente, magari ricordiamoci di aggiungerlo allo schema quando lo si ridiscute

**Comment by xrmx** [comment]
E c'è anche da capire se vogliamo usare il db o farlo tutto lato frontend facendo query su elastic search (anche se il logo significa o indicizzare quello o comunque fare query al db)

**Comment by francescozaia** [comment]
L'ente sono le organizzazioni su GitHub, i dati quelli presenti sul `publisher_settings.yml`. Tirerei fuori tutto da DB

**Comment by xrmx** [comment]
@francescozaia per tipologia dell'ente intendo l'ultimo filtro in basso a sx nel mockup.

**Comment by francescozaia** [comment]
Ah beh sì, di quello per ora non curiamoci, con ogni probabilità sarà un attributo nello yaml suddetto.

**Comment by xrmx** [comment]
C'è una versione base in #96
